export const BRAND = {
  /** Visible company name — used in UI headings, report headers, page titles */
  name: 'Slattery Auctions',
  /** Short brand identifier for logo monogram */
  logoMonogram: 'S',
  /** Full app title for browser tab / metadata */
  appTitle: 'Slattery Auctions Book-in',
  /** Page metadata description */
  appDescription: 'Asset book-in tool',
  /** Report header label */
  reportHeader: 'Slattery Auctions \u2014 Condition Report',
  /** Report footer text */
  reportFooter: 'Generated by Slattery Auctions Asset Book-In',
  /** Domain used in QR codes — change this one value to update all QR codes */
  domain: 'assetbookintool.com',
} as const
