'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ChevronLeft, Printer } from 'lucide-react'

interface ReportClientProps {
  assetId: string
  title: string
  fieldsText: string
  description: string | null
  photoUrls: string[]
}

export function ReportClient({ assetId, title, fieldsText, description, photoUrls }: ReportClientProps) {
  const [desc, setDesc] = useState(description)
  const [loadingDesc, setLoadingDesc] = useState(!description)
  const [descError, setDescError] = useState(false)

  useEffect(() => {
    if (description) return
    fetch('/api/describe', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ assetId }),
    })
      .then(r => { if (!r.ok) throw new Error('API error'); return r.json() })
      .then(d => { if (d.description) setDesc(d.description); else setDescError(true) })
      .catch(() => setDescError(true))
      .finally(() => setLoadingDesc(false))
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <>
      {/* Screen toolbar — hidden when printing */}
      <div className="print:hidden max-w-2xl mx-auto px-4 pt-6 pb-4 flex items-center justify-between">
        <Link href={`/assets/${assetId}/output`} className="inline-flex items-center gap-1 text-sm text-white/65 hover:text-white">
          <ChevronLeft className="w-4 h-4" />
          Output
        </Link>
        <button
          type="button"
          onClick={() => window.print()}
          className="inline-flex items-center gap-2 bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-semibold px-4 py-2 rounded-lg transition-colors"
        >
          <Printer className="w-4 h-4" />
          Print / Save PDF
        </button>
      </div>

      {/* Report content */}
      <div className="report-page max-w-2xl mx-auto px-4 pb-12 print:px-0 print:pb-0 print:max-w-none">
        {/* Header */}
        <div className="mb-6 pb-4 border-b border-white/10 print:border-gray-300">
          <div className="flex items-start justify-between gap-4">
            <div>
              <p className="text-xs text-white/40 print:text-gray-500 uppercase tracking-widest font-semibold mb-1">Slattery Auctions — Condition Report</p>
              <h1 className="text-2xl font-bold text-white print:text-black">{title}</h1>
            </div>
            <img
              src={`https://api.qrserver.com/v1/create-qr-code/?size=64x64&bgcolor=ffffff&color=000000&data=${encodeURIComponent(`https://assetbookintool.com/assets/${assetId}/output`)}`}
              alt="QR"
              width={64}
              height={64}
              className="rounded flex-shrink-0"
            />
          </div>
        </div>

        {/* Photos */}
        {photoUrls.length > 0 && (
          <div className="mb-6">
            <h2 className="text-xs font-semibold text-white/40 print:text-gray-500 uppercase tracking-widest mb-3">Photos</h2>
            <div className="grid grid-cols-3 gap-2 print:grid-cols-4">
              {photoUrls.map((url, i) => (
                <img
                  key={i}
                  src={url}
                  alt={`Photo ${i + 1}`}
                  loading="lazy"
                  className="w-full aspect-square object-cover rounded-lg print:rounded"
                />
              ))}
            </div>
          </div>
        )}

        {/* Fields */}
        <div className="mb-6">
          <h2 className="text-xs font-semibold text-white/40 print:text-gray-500 uppercase tracking-widest mb-3">Salesforce Fields</h2>
          <pre className="text-sm font-mono whitespace-pre-wrap text-white/80 print:text-black bg-white/[0.04] print:bg-gray-50 rounded-xl print:rounded p-4 print:border print:border-gray-200 leading-relaxed">
            {fieldsText}
          </pre>
        </div>

        {/* Description */}
        <div className="mb-6">
          <h2 className="text-xs font-semibold text-white/40 print:text-gray-500 uppercase tracking-widest mb-3">Auction Description</h2>
          {loadingDesc ? (
            <p className="text-sm text-white/40 italic">Generating description…</p>
          ) : desc ? (
            <pre className="text-sm font-sans whitespace-pre-wrap text-white/80 print:text-black leading-relaxed">
              {desc}
            </pre>
          ) : descError ? (
            <p className="text-sm text-red-400/80 italic">Description generation failed. Go back to Output to retry.</p>
          ) : (
            <p className="text-sm text-white/40 italic">No description generated yet.</p>
          )}
        </div>

        {/* Footer */}
        <div className="pt-4 border-t border-white/10 print:border-gray-300 text-xs text-white/30 print:text-gray-400">
          Generated by Slattery Auctions Asset Book-In · assetbookintool.com
        </div>
      </div>

      <style>{`
        @media print {
          body { background: white !important; color: black !important; }
          .print\\:hidden { display: none !important; }
        }
      `}</style>
    </>
  )
}
