import type { AssetSchema } from '../types'

export const agricultureSchema: AssetSchema = {
  assetType: 'agriculture',
  displayName: 'Agriculture',
  subtypes: [
    { key: 'air_seeder',        label: 'Air Seeder' },
    { key: 'baler',             label: 'Baler' },
    { key: 'combine_harvester', label: 'Combine Harvester' },
    { key: 'coupe',             label: 'Coupe' },
    { key: 'disc_seeder',       label: 'Disc Seeder' },
    { key: 'forestry',          label: 'Forestry' },
    { key: 'grain_auger',       label: 'Grain Auger' },
    { key: 'mower_conditioner', label: 'Mower/Conditioner' },
    { key: 'other',             label: 'Other' },
    { key: 'plough',            label: 'Plough' },
    { key: 'spray_rig',         label: 'Spray Rig' },
    { key: 'tractor',           label: 'Tractor' },
  ],
  hasGlassValuation: false,
  fields: [
    { key: 'pin',                        label: 'PIN',                    sfOrder: 1,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Build plate on frame or cab: Product Identification Number. 17-char alphanumeric starting with manufacturer code. Never infer — only extract if directly visible.' },
    { key: 'serial',                     label: 'Serial',                 sfOrder: 2,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Build plate on frame, cab door, or chassis: Serial Number field. Format varies (e.g. CD6130RABCD12345). Never infer — only extract if directly visible.' },
    { key: 'vin',                        label: 'VIN',                    sfOrder: 3,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Build plate or chassis rail: 17-char VIN if present. Never infer — only extract if directly visible.' },
    { key: 'type',                       label: 'Type',                   sfOrder: 4,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'make',                       label: 'Make',                   sfOrder: 5,  inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Build plate or exterior badge: manufacturer (e.g. John Deere, Case IH, New Holland, Fendt, Massey Ferguson, Kubota, AGCO, Claas, Challenger). Read exactly as shown.' },
    { key: 'hourmeter',                  label: 'Hourmeter',              sfOrder: 6,  inputType: 'number',   aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Cab instrument cluster: hourmeter or engine hours display. Digits only. Only extract if clearly readable from photo — do NOT guess.' },
    { key: 'model',                      label: 'Model',                  sfOrder: 7,  inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Build plate or body decal: model designation (e.g. 6130R, Puma 185, T7.210, 8370R, S790, Vario 936). Read exactly as printed — include suffixes.' },
    { key: 'year',                       label: 'Year',                   sfOrder: 8,  inputType: 'number',   aiExtractable: true,  required: true,  aiHint: 'Build plate: Year of Manufacture or DOM field. 4-digit year only. If not visible, estimate from serial number decode or model era.' },
    { key: 'odometer',                   label: 'Odometer',               sfOrder: 9,  inputType: 'number',   aiExtractable: false, inspectionPriority: true, required: false },
    { key: 'engine_manufacturer',        label: 'Engine Manufacturer',    sfOrder: 10, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Engine bay badge or build plate. Infer from make if not visible: John Deere→PowerTech, Case IH→FPT, Fendt/AGCO→AGCO Power, Claas→Mercedes-Benz.' },
    { key: 'engine_model',               label: 'Engine Model',           sfOrder: 11, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Engine bay plate or infer from make/model/year. Examples: JD 6130R→6068PowerTech, CaseIH Puma 185→FPT Cursor 9, NH T7.210→FPT NEF.' },
    { key: 'engine_number',              label: 'Engine Number',          sfOrder: 12, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'horsepower',                 label: 'Horsepower',             sfOrder: 13, inputType: 'number',   aiExtractable: true,  required: false, aiHint: 'Infer from make/model/year spec. Engine HP (not PTO): JD 6130R=130hp, CaseIH Puma185=185hp, NH T7.210=210hp. Digits only, no units.' },
    { key: 'fuel_type',                  label: 'Fuel Type',              sfOrder: 14, inputType: 'select',   options: ['Diesel', 'Petrol', 'Electric', 'LPG'], aiExtractable: true,  required: false, aiHint: 'Almost always Diesel for agricultural equipment. Only return Petrol/Electric/LPG if clearly evidenced by badge or visible fuel cap label.' },
    { key: 'drive_type',                 label: 'Drive Type',             sfOrder: 15, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Visible axle/wheel configuration or infer from model: MFWD (front axle drive), 4WD (articulated), 2WD (rear only). Most modern tractors are MFWD or 4WD.' },
    { key: 'transmission',               label: 'Transmission',           sfOrder: 16, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer from make/model: JD AutoPowr IVT, CaseIH Powershift, NH AutoCommand CVT, Fendt Vario CVT, Massey Ferguson Dyna-VT. Model-specific constant.' },
    { key: 'cabin',                      label: 'Cabin',                  sfOrder: 17, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Visible from exterior/interior photos: enclosed cab with ROPS (Air Con Cab), open ROPS frame, or no cab. Note air conditioning if visible.' },
    { key: 'three_point_linkage_front',  label: '3 Point Linkage Front',  sfOrder: 18, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'three_point_linkage_rear',   label: '3 Point Linkage Rear',   sfOrder: 19, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'tyres_front',                label: 'Tyres Front',            sfOrder: 20, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Front tyre sidewall text: size format W/AR (e.g. 540/65R28, 420/85R28). Read from front tyre if visible in photo.' },
    { key: 'tyres_rear',                 label: 'Tyres Rear',             sfOrder: 21, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Rear tyre sidewall text: size format W/AR (e.g. 710/70R42, 650/85R38). Read from rear tyre if visible in photo.' },
    { key: 'pto',                        label: 'PTO',                    sfOrder: 22, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'remotes',                    label: 'Remotes',                sfOrder: 23, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'number_of_remotes',          label: 'Number of Remotes',      sfOrder: 24, inputType: 'number',   aiExtractable: false, required: false },
    { key: 'ops_manager',                label: 'Ops Manager',            sfOrder: 25, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'attachments',                label: 'Attachments',            sfOrder: 26, inputType: 'textarea', aiExtractable: false, required: false },
    { key: 'extras',                     label: 'Extras',                 sfOrder: 27, inputType: 'textarea', aiExtractable: false, required: false },
  ],
  descriptionTemplate: (_fields, _subtype) => '',
}
