import type { AssetSchema } from '../types'

export const agricultureSchema: AssetSchema = {
  assetType: 'agriculture',
  displayName: 'Agriculture',
  subtypes: [
    { key: 'tractor',     label: 'Tractor' },
    { key: 'header',      label: 'Header / Combine' },
    { key: 'sprayer',     label: 'Sprayer' },
    { key: 'planter',     label: 'Planter' },
    { key: 'baler',       label: 'Baler' },
    { key: 'cultivation', label: 'Cultivation' },
  ],
  hasGlassValuation: false,
  fields: [
    { key: 'pin',                        label: 'PIN',                    sfOrder: 1,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false },
    { key: 'serial',                     label: 'Serial',                 sfOrder: 2,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false },
    { key: 'vin',                        label: 'VIN',                    sfOrder: 3,  inputType: 'text',     aiExtractable: true,  required: false },
    { key: 'type',                       label: 'Type',                   sfOrder: 4,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'make',                       label: 'Make',                   sfOrder: 5,  inputType: 'text',     aiExtractable: true,  required: true  },
    { key: 'hourmeter',                  label: 'Hourmeter',              sfOrder: 6,  inputType: 'number',   aiExtractable: false, inspectionPriority: true, required: false },
    { key: 'model',                      label: 'Model',                  sfOrder: 7,  inputType: 'text',     aiExtractable: true,  required: true  },
    { key: 'year',                       label: 'Year',                   sfOrder: 8,  inputType: 'number',   aiExtractable: true,  required: true  },
    { key: 'odometer',                   label: 'Odometer',               sfOrder: 9,  inputType: 'number',   aiExtractable: false, inspectionPriority: true, required: false },
    { key: 'engine_manufacturer',        label: 'Engine Manufacturer',    sfOrder: 10, inputType: 'text',     aiExtractable: true,  required: false },
    { key: 'engine_model',               label: 'Engine Model',           sfOrder: 11, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'engine_number',              label: 'Engine Number',          sfOrder: 12, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'horsepower',                 label: 'Horsepower',             sfOrder: 13, inputType: 'number',   aiExtractable: false, required: false },
    { key: 'fuel_type',                  label: 'Fuel Type',              sfOrder: 14, inputType: 'select',   options: ['Diesel', 'Petrol', 'Electric', 'LPG'], aiExtractable: false, required: false },
    { key: 'drive_type',                 label: 'Drive Type',             sfOrder: 15, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'transmission',               label: 'Transmission',           sfOrder: 16, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'cabin',                      label: 'Cabin',                  sfOrder: 17, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'three_point_linkage_front',  label: '3 Point Linkage Front',  sfOrder: 18, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'three_point_linkage_rear',   label: '3 Point Linkage Rear',   sfOrder: 19, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'tyres_front',                label: 'Tyres Front',            sfOrder: 20, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'tyres_rear',                 label: 'Tyres Rear',             sfOrder: 21, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'pto',                        label: 'PTO',                    sfOrder: 22, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'remotes',                    label: 'Remotes',                sfOrder: 23, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'number_of_remotes',          label: 'Number of Remotes',      sfOrder: 24, inputType: 'number',   aiExtractable: false, required: false },
    { key: 'ops_manager',                label: 'Ops Manager',            sfOrder: 25, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'attachments',                label: 'Attachments',            sfOrder: 26, inputType: 'textarea', aiExtractable: false, required: false },
    { key: 'extras',                     label: 'Extras',                 sfOrder: 27, inputType: 'textarea', aiExtractable: false, required: false },
  ],
  descriptionTemplate: (_fields, _subtype) => '',
}
