import type { AssetSchema } from '../types'

export const caravanSchema: AssetSchema = {
  assetType: 'caravan',
  displayName: 'Caravan / Motor Home',
  subtypes: [
    { key: 'camper_trailer', label: 'Camper Trailer' },
    { key: 'caravan',        label: 'Caravan' },
    { key: 'coupe',          label: 'Coupe' },
    { key: 'motorhome',      label: 'Motorhome' },
    { key: 'other',          label: 'Other' },
  ],
  hasGlassValuation: true,
  fields: [
    { key: 'make',                label: 'Make',                sfOrder: 1,  inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Build plate or exterior badge: manufacturer name (e.g. Jayco, Coromal, New Age, Roadstar, Winnebago, Sunliner, Adria, Jurgens, Lotus, Avida). Check rear badge, side decal, and build plate.' },
    { key: 'model',               label: 'Model',               sfOrder: 2,  inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Build plate or exterior decal: model designation (e.g. Silverline, Outback, Journey, Sterling). Read exactly as printed. Use your knowledge of common Australian caravan models.' },
    { key: 'year',                label: 'Year',                sfOrder: 3,  inputType: 'number',   aiExtractable: true,  required: true,  aiHint: 'Build plate: Year of Manufacture or DOM. 4-digit year only. If not visible, estimate from style/features.' },
    { key: 'type',                label: 'Type',                sfOrder: 4,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Caravan category: e.g. "Pop-Top", "Full-Height", "Slide-Out", "Bunk Van", "Family". Visible from exterior profile.' },
    { key: 'vin',                 label: 'VIN',                 sfOrder: 5,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Build plate or compliance plate: 17-character VIN. Never infer — only extract if directly visible.' },
    { key: 'serial',              label: 'Serial',              sfOrder: 6,  inputType: 'text',     aiExtractable: false, inspectionPriority: false, required: false },
    { key: 'colour',              label: 'Colour',              sfOrder: 8,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Visible from exterior photos: main body colour (e.g. "White", "Silver/White", "Cream").' },
    { key: 'engine_manufacturer', label: 'Engine Manufacturer', sfOrder: 9,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Motor home only: engine badge or build plate. e.g. Cummins, Mercedes-Benz, Ford, Hino. Null for towed caravans (no engine).' },
    { key: 'engine_model',        label: 'Engine Model',        sfOrder: 10, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Motorhome only: engine model from badge or plate (e.g. ISB 5.9, OM906, 5.4L V8). Null for towed caravans.' },
    { key: 'transmission',        label: 'Transmission',        sfOrder: 7,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Motorhome only: "Automatic" or "Manual". Null for towed caravans.' },
    { key: 'trailer_length',      label: 'Length (ft)',         sfOrder: 15, inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Length of caravan body in feet (Australian standard). Use build plate if visible, or estimate from photos. Common sizes: 16ft, 18ft, 19ft, 21ft, 22ft.' },
    { key: 'suspension',          label: 'Suspension',          sfOrder: 21, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Visible from undercarriage or chassis photos: e.g. "Independent Coil", "Leaf Spring", "Al-Ko Independent", "Rocker Roller". Common on Australian caravans: Al-Ko, Cruisemaster, Simplicity.' },
    { key: 'brakes',              label: 'Brakes',              sfOrder: 22, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'From undercarriage or wheel area photos: "Electric Brakes" (most common Australian standard), "Disc Brakes", "Hydraulic Brakes".' },
    { key: 'tyres',               label: 'Tyres',               sfOrder: 12, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'From tyre sidewall if visible: size and brand (e.g. "235/75R15 Maxxis", "215/70R15"). Note if spares are visible.' },
    { key: 'registration',        label: 'Registration',        sfOrder: 13, inputType: 'text',     aiExtractable: false, inspectionPriority: true, required: false },
    { key: 'odometer',            label: 'Odometer',            sfOrder: 14, inputType: 'number',   aiExtractable: false, inspectionPriority: true, required: false },
    { key: 'tare',                label: 'Tare',                sfOrder: 16, inputType: 'number',   aiExtractable: true,  required: false, aiHint: 'Build plate: Tare Mass in kg. Only extract if directly visible.' },
    { key: 'gvm',                 label: 'GVM',                 sfOrder: 18, inputType: 'number',   aiExtractable: true,  required: false, aiHint: 'Build plate: GVM in kg. Only extract if directly visible.' },
    { key: 'atm',                 label: 'ATM',                 sfOrder: 20, inputType: 'number',   aiExtractable: true,  required: false, aiHint: 'Build plate: Aggregate Trailer Mass (ATM) in kg. Only extract if directly visible.' },
    { key: 'extras',              label: 'Extras',              sfOrder: 25, inputType: 'textarea', aiExtractable: true,  required: false, aiHint: 'Visible from interior/exterior photos: list fitted extras separated by commas. Look for: solar panels (note wattage if badge visible), air conditioning (roof-mounted), TV antenna, awning (roll-out or slide-out), annexe, generator, bike rack, rear bumper bar, external shower, external kitchen, slide-out pantry, bunk beds, island bed, ensuite, fireplace, dishwasher.' },
    { key: 'damage',              label: 'Damage',              sfOrder: 27, inputType: 'textarea', aiExtractable: true,  required: false, aiHint: 'Visible damage from exterior/interior photos: dents, delamination, water damage marks, torn upholstery, cracked windows, damaged awning. Only note what is clearly visible.' },
    { key: 'height',              label: 'Height',              sfOrder: 17, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'width',               label: 'Width',               sfOrder: 19, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'rims',                label: 'Rims',                sfOrder: 24, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'compliance_date',     label: 'Compliance Date',     sfOrder: 23, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'owners_manual',       label: "Owner's Manual",      sfOrder: 26, inputType: 'text',     aiExtractable: false, required: false },
  ],
  descriptionTemplate: (_fields, _subtype) => '',
}
