import type { AssetSchema } from '../types'

export const caravanSchema: AssetSchema = {
  assetType: 'caravan',
  displayName: 'Caravan / Motor Home',
  subtypes: [
    { key: 'caravan',        label: 'Caravan' },
    { key: 'motor_home',     label: 'Motor Home' },
    { key: 'camper_trailer', label: 'Camper Trailer' },
  ],
  hasGlassValuation: true,
  fields: [
    { key: 'make',                label: 'Make',                sfOrder: 1,  inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Build plate or exterior badge: manufacturer name (e.g. Jayco, Coromal, New Age, Roadstar, Winnebago, Sunliner, Adria).' },
    { key: 'model',               label: 'Model',               sfOrder: 2,  inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Build plate: model designation. Read exactly as printed.' },
    { key: 'year',                label: 'Year',                sfOrder: 3,  inputType: 'number',   aiExtractable: true,  required: true,  aiHint: 'Build plate: Year of Manufacture or DOM. 4-digit year only.' },
    { key: 'type',                label: 'Type',                sfOrder: 4,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'vin',                 label: 'VIN',                 sfOrder: 5,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Build plate or compliance plate: 17-character VIN. Never infer — only extract if directly visible.' },
    { key: 'serial',              label: 'Serial',              sfOrder: 6,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Build plate: Serial Number. Never infer — only extract if directly visible.' },
    { key: 'transmission',        label: 'Transmission',        sfOrder: 7,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'colour',              label: 'Colour',              sfOrder: 8,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'engine_manufacturer', label: 'Engine Manufacturer', sfOrder: 9,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Motor home only: engine badge or build plate. e.g. Cummins, Mercedes-Benz, Ford. Null for towed caravans (no engine).' },
    { key: 'engine_model',        label: 'Engine Model',        sfOrder: 10, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'engine_number',       label: 'Engine Number',       sfOrder: 11, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'tyres',               label: 'Tyres',               sfOrder: 12, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'registration',        label: 'Registration',        sfOrder: 13, inputType: 'text',     aiExtractable: false, inspectionPriority: true, required: false },
    { key: 'odometer',            label: 'Odometer',            sfOrder: 14, inputType: 'number',   aiExtractable: false, inspectionPriority: true, required: false },
    { key: 'trailer_length',      label: 'Trailer Length',      sfOrder: 15, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'tare',                label: 'Tare',                sfOrder: 16, inputType: 'number',   aiExtractable: false, required: false },
    { key: 'height',              label: 'Height',              sfOrder: 17, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'gvm',                 label: 'GVM',                 sfOrder: 18, inputType: 'number',   aiExtractable: false, required: false },
    { key: 'width',               label: 'Width',               sfOrder: 19, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'atm',                 label: 'ATM',                 sfOrder: 20, inputType: 'number',   aiExtractable: false, required: false },
    { key: 'suspension',          label: 'Suspension',          sfOrder: 21, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'brakes',              label: 'Brakes',              sfOrder: 22, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'compliance_date',     label: 'Compliance Date',     sfOrder: 23, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'rims',                label: 'Rims',                sfOrder: 24, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'extras',              label: 'Extras',              sfOrder: 25, inputType: 'textarea', aiExtractable: false, required: false },
    { key: 'owners_manual',       label: "Owner's Manual",      sfOrder: 26, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'damage',              label: 'Damage',              sfOrder: 27, inputType: 'textarea', aiExtractable: false, required: false },
  ],
  descriptionTemplate: (_fields, _subtype) => '',
}
