import type { AssetSchema } from '../types'

export const earthmovingSchema: AssetSchema = {
  assetType: 'earthmoving',
  displayName: 'Earthmoving',
  subtypes: [
    { key: 'excavator',    label: 'Excavator' },
    { key: 'dozer',        label: 'Dozer' },
    { key: 'grader',       label: 'Grader' },
    { key: 'wheel_loader', label: 'Wheel Loader' },
    { key: 'skid_steer',   label: 'Skid Steer / CTL' },
    { key: 'backhoe',      label: 'Backhoe' },
    { key: 'telehandler',  label: 'Telehandler' },
  ],
  hasGlassValuation: false,
  fields: [
    { key: 'pin',                 label: 'PIN',                sfOrder: 1,  inputType: 'text',     aiExtractable: true,  required: false },
    { key: 'serial',              label: 'Serial',             sfOrder: 2,  inputType: 'text',     aiExtractable: true,  required: false },
    { key: 'vin',                 label: 'VIN',                sfOrder: 3,  inputType: 'text',     aiExtractable: true,  required: false },
    { key: 'type',                label: 'Type',               sfOrder: 4,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'make',                label: 'Make',               sfOrder: 5,  inputType: 'text',     aiExtractable: true,  required: true  },
    { key: 'hourmeter',           label: 'Hourmeter',          sfOrder: 6,  inputType: 'number',   aiExtractable: false, required: false },
    { key: 'model',               label: 'Model',              sfOrder: 7,  inputType: 'text',     aiExtractable: true,  required: true  },
    { key: 'year',                label: 'Year',               sfOrder: 8,  inputType: 'number',   aiExtractable: true,  required: true  },
    { key: 'odometer',            label: 'Odometer',           sfOrder: 9,  inputType: 'number',   aiExtractable: false, required: false },
    { key: 'engine_manufacturer', label: 'Engine Manufacturer',sfOrder: 10, inputType: 'text',     aiExtractable: true,  required: false },
    { key: 'engine_model',        label: 'Engine Model',       sfOrder: 11, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'engine_number',       label: 'Engine Number',      sfOrder: 12, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'horsepower',          label: 'Horsepower',         sfOrder: 13, inputType: 'number',   aiExtractable: false, required: false },
    { key: 'gross_hp',            label: 'Gross HP',           sfOrder: 14, inputType: 'number',   aiExtractable: false, required: false },
    { key: 'fuel_type',           label: 'Fuel Type',          sfOrder: 15, inputType: 'select',   options: ['Diesel', 'Petrol', 'Electric', 'LPG'], aiExtractable: false, required: false },
    { key: 'emissions_tier',      label: 'Emissions Tier',     sfOrder: 16, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'drive_type',          label: 'Drive Type',         sfOrder: 17, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'transmission',        label: 'Transmission',       sfOrder: 18, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'speeds',              label: 'Speeds',             sfOrder: 19, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'torque_rpm',          label: 'Torque RPM',         sfOrder: 20, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'boom_length',         label: 'Boom Length',        sfOrder: 21, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'steering',            label: 'Steering',           sfOrder: 22, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'final_drive',         label: 'Final Drive',        sfOrder: 23, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'cabin',               label: 'Cabin',              sfOrder: 24, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'operator_station',    label: 'Operator Station',   sfOrder: 25, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'attachments',         label: 'Attachments',        sfOrder: 26, inputType: 'textarea', aiExtractable: false, required: false },
    { key: 'config',              label: 'Config',             sfOrder: 27, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'screen_size',         label: 'Screen Size',        sfOrder: 28, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'tare',                label: 'Tare',               sfOrder: 29, inputType: 'number',   aiExtractable: false, required: false },
    { key: 'capacity',            label: 'Capacity',           sfOrder: 30, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'rims',                label: 'Rims',               sfOrder: 31, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'pto',                 label: 'PTO',                sfOrder: 32, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'remotes',             label: 'Remotes',            sfOrder: 33, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'extras',              label: 'Extras',             sfOrder: 34, inputType: 'textarea', aiExtractable: false, required: false },
  ],
  descriptionTemplate: (_fields, _subtype) => '',
}
