import type { AssetSchema } from '../types'

export const earthmovingSchema: AssetSchema = {
  assetType: 'earthmoving',
  displayName: 'Earthmoving',
  subtypes: [
    { key: 'attachments',               label: 'Attachments' },
    { key: 'backhoe',                   label: 'Backhoe' },
    { key: 'bulldozer_crawler_tractor', label: 'Bulldozer/Crawler Tractor' },
    { key: 'compactor',                 label: 'Compactor' },
    { key: 'conveyors_stackers',        label: 'Conveyors / Stackers' },
    { key: 'coupe',                     label: 'Coupe' },
    { key: 'crusher',                   label: 'Crusher' },
    { key: 'dump_truck',                label: 'Dump Truck' },
    { key: 'excavator',                 label: 'Excavator' },
    { key: 'motor_grader',              label: 'Motor Grader' },
    { key: 'motor_scraper',             label: 'Motor Scraper' },
    { key: 'other',                     label: 'Other' },
    { key: 'scraper',                   label: 'Scraper' },
    { key: 'screener',                  label: 'Screener' },
    { key: 'skid_steer_loader',         label: 'Skid Steer Loader' },
    { key: 'tracked_loader',            label: 'Tracked Loader' },
    { key: 'tracked_skid_steer_loader', label: 'Tracked Skid Steer Loader' },
    { key: 'washing',                   label: 'Washing' },
    { key: 'wheel_loader',              label: 'Wheel Loader' },
  ],
  hasGlassValuation: false,
  fields: [
    { key: 'pin',                 label: 'PIN',                sfOrder: 1,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Build plate on frame/boom: Product Identification Number. Cat PIN: 17-char alphanumeric. Komatsu/Hitachi use serial number instead. Never infer — only extract if directly visible.' },
    { key: 'serial',              label: 'Serial',             sfOrder: 2,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Build plate on chassis/frame/boom. Format varies: Komatsu (e.g. PC200-8 #12345), Hitachi (e.g. ZX200-3 #001234), Volvo (e.g. EC220DL #123456). Never infer — only extract if directly visible.' },
    { key: 'vin',                 label: 'VIN',                sfOrder: 3,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Build plate: 17-char VIN if present — more common on wheel-based machines (graders, wheel loaders). Excavators/dozers typically use PIN instead. Never infer.' },
    { key: 'type',                label: 'Type',               sfOrder: 4,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer from subtype/photos. e.g. Hydraulic Excavator, Crawler Dozer, Wheel Loader, Motor Grader, Skid Steer Loader, Backhoe Loader, Vibrating Roller.' },
    { key: 'make',                label: 'Make',               sfOrder: 5,  inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Build plate or cab badge. Common earthmoving manufacturers: Caterpillar (Cat), Komatsu, Hitachi, Volvo CE, Liebherr, John Deere, CASE, Doosan, Hyundai, Bobcat, Terex, Sandvik.' },
    { key: 'hourmeter',           label: 'Hourmeter',          sfOrder: 6,  inputType: 'number',   aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Instrument panel hour meter (labelled "HRS", "SMR", or clock icon). Digits only. Extract only if clearly readable in cab/dashboard photo — this is the primary usage metric for earthmoving equipment.' },
    { key: 'model',               label: 'Model',              sfOrder: 7,  inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Build plate or cab badge. Read exactly as printed including generation suffix (e.g. 320D, 320D2, PC200-8, PC200LC-8, ZX200-3, EC220DL, 950GC, D6T). Include model variant/series number.' },
    { key: 'year',                label: 'Year',               sfOrder: 8,  inputType: 'number',   aiExtractable: true,  required: true,  aiHint: 'Build plate "Year of Manufacture" or "DOM". 4-digit year. Cat: year in PIN chars 9-13. Komatsu: from serial prefix. Estimate from model generation if build plate not legible.' },
    { key: 'odometer',            label: 'Odometer',           sfOrder: 9,  inputType: 'number',   aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Dashboard odometer — relevant for wheeled machines (loaders, graders, backhoes). Digits only in km. Extract only if clearly readable. Tracked machines (excavators, dozers) rarely have odometers — return null.' },
    { key: 'engine_manufacturer', label: 'Engine Manufacturer',sfOrder: 10, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Cam cover badge or infer from make: Cat→Caterpillar; Komatsu→Komatsu (SAA) or Cummins; Hitachi→Isuzu or Hino; Volvo CE→Volvo Penta; John Deere→JD PowerTech; CASE/Doosan→Cummins.' },
    { key: 'engine_model',        label: 'Engine Model',       sfOrder: 11, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer from make/model/year. Cat 320D/D2→C7.1; Cat 323→C7.1; Cat 330→C9.3; Komatsu PC200-8→SAA6D107E-1; PC300-8→SAA6D114E-3; Volvo EC220→D6E; Hitachi ZX200→Isuzu 4HK1; ZX350→Isuzu 6HK1. Return engine model code.' },
    { key: 'engine_number',       label: 'Engine Number',      sfOrder: 12, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'horsepower',          label: 'Horsepower',         sfOrder: 13, inputType: 'number',   aiExtractable: true,  required: false, aiHint: 'Infer net HP from make/model/year. Digits only. Cat 320D→148hp; Cat 330→270hp; PC200-8→148hp; PC300-8→228hp; ZX200→148hp; ZX350→258hp; EC220→170hp; EC300→229hp. Use rated/net HP.' },
    { key: 'gross_hp',            label: 'Gross HP',           sfOrder: 14, inputType: 'number',   aiExtractable: true,  required: false, aiHint: 'Gross (SAE J1995) HP — typically 5–10% higher than net HP. Infer from model. Digits only. e.g. Cat 320D gross ≈ 162hp. Null if not confidently known.' },
    { key: 'fuel_type',           label: 'Fuel Type',          sfOrder: 15, inputType: 'select',   options: ['Diesel', 'Petrol', 'Electric', 'LPG'], aiExtractable: true,  required: false, aiHint: 'Virtually all earthmoving equipment is Diesel. Only return non-Diesel if clearly evidenced: electric motor/battery visible, LPG badge/filler. Default to Diesel.' },
    { key: 'emissions_tier',      label: 'Emissions Tier',     sfOrder: 16, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer from year: pre-2006→Tier 2; 2006–2011→Tier 3/Stage IIIA; 2011–2014→Tier 4 Interim/Stage IIIB; 2014+→Tier 4 Final/Stage IV. Australia typically follows EU stages.' },
    { key: 'drive_type',          label: 'Drive Type',         sfOrder: 17, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer from machine type and photos. Excavators/dozers/tracked loaders = Track Drive. Wheel loaders/graders/backhoes = 4WD. Skid steers = 4WD (wheeled) or Track Drive (CTL). e.g. "Track Drive", "4WD".' },
    { key: 'transmission',        label: 'Transmission',       sfOrder: 18, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer from machine type: Excavators→Hydrostatic; Wheel loaders→Powershift (Cat/ZF); Dozers→Powershift or Hydrostatic; Graders→Powershift. e.g. "Hydrostatic", "Automatic Powershift (Cat)".' },
    { key: 'speeds',              label: 'Speeds',             sfOrder: 19, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'torque_rpm',          label: 'Torque RPM',         sfOrder: 20, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'boom_length',         label: 'Boom Length',        sfOrder: 21, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'For excavators: boom length is the main boom from pivot to stick pivot — infer from make/model spec (e.g. Cat 320D standard boom ≈ 5.7m). Not usually visible directly in photo but confidently inferable from model. Null for non-excavator machines.' },
    { key: 'steering',            label: 'Steering',           sfOrder: 22, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer from machine type/make: Wheel loaders/graders = articulated frame steering; Excavators/dozers/CTLs = no steering (track steer via dual levers/joystick); Backhoes = rear-axle steer (standard 2WD steer) + optional 4WD coordinated. e.g. \'Articulated Frame\', \'Track-Driven\'.' },
    { key: 'final_drive',         label: 'Final Drive',        sfOrder: 23, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer from machine type/make/model: Excavators→Planetary hydraulic final drive; Dozers→Multi-disc clutch or hydrostatic (Cat D6T→Powershift planetary); Wheel loaders→Axle planetary. e.g. \'Planetary\', \'Hydrostatic planetary\'.' },
    { key: 'cabin',               label: 'Cabin',              sfOrder: 24, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer from exterior photos. Open frame = ROPS; enclosed glass cab = ROPS/FOPS. Most modern excavators/loaders have enclosed cab. e.g. "Enclosed ROPS/FOPS Cab", "Open ROPS Frame".' },
    { key: 'operator_station',    label: 'Operator Station',   sfOrder: 25, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'attachments',         label: 'Attachments',        sfOrder: 26, inputType: 'textarea', aiExtractable: true,  required: false, aiHint: 'Visible attachments in photos: bucket (GP/ditching/rock), hydraulic hammer, auger, ripper (dozer), thumb, tilt bucket, pallet forks, coupler plate. Describe each item visible. Note brand if badge readable (Kinshofer, Caterpillar, Roo-Te, Epiroc).' },
    { key: 'config',              label: 'Config',             sfOrder: 27, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Configuration extras visible from photos: long reach arm (longer stick/arm visible), reduced tail swing, zero-tail-swing (tail swing within track width), high-walk undercarriage, extended carriage. Null if standard configuration.' },
    { key: 'screen_size',         label: 'Screen Size',        sfOrder: 28, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'tare',                label: 'Tare',               sfOrder: 29, inputType: 'number',   aiExtractable: true,  required: false, aiHint: 'Operating weight in kg — infer from make/model/year specs. Digits only. Cat 320D≈20800kg; Cat 330≈30600kg; PC200-8≈20100kg; PC300-8≈30000kg; ZX200≈20300kg; EC220≈22000kg. Use standard operating weight.' },
    { key: 'capacity',            label: 'Capacity',           sfOrder: 30, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'For wheel loaders: bucket capacity in m³, infer from model spec (e.g. Cat 950GC = 3.1m³ general purpose). For dump trucks: payload in tonnes, infer from model. For skid steers: rated operating capacity in kg. Format: value + unit (e.g. \'3.1m³\', \'12t\', \'800kg\').' },
    { key: 'rims',                label: 'Rims',               sfOrder: 31, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Tyre rim type visible in wheel/tyre photos. Wheeled machines only: Steel painted rims (standard), Alloy rims (premium). Null for tracked machines (no rims). e.g. \'Steel\', \'Alloy\'.' },
    { key: 'pto',                 label: 'PTO',                sfOrder: 32, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'For crawler tractors and backhoes only. Rear PTO stub visible in rear photo. Infer from model if visible: standard = 540/1000rpm. Null for excavators, bulldozers, loaders, graders (no PTO).' },
    { key: 'remotes',             label: 'Remotes',            sfOrder: 33, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'For backhoes and crawler tractors: count rear remote hydraulic SCV coupler pairs visible in rear photo, or infer from make/model spec. Null for excavators/dozers/loaders (no remotes).' },
    { key: 'extras',              label: 'Extras',             sfOrder: 34, inputType: 'textarea', aiExtractable: true,  required: false, aiHint: 'Visible extras from cab/exterior photos: AC cab, quick hitch, GPS grade control (brand: Topcon, Trimble, Leica, Cat GRADE), rear-view camera, dozer blade, beacon, ripper, counterweight configuration, blade type (PAT, semi-U, straight). Note all visible options and brand names.' },
  ],
  descriptionTemplate: (_fields, _subtype) => '',
}
