import type { AssetSchema } from '../types'

export const earthmovingSchema: AssetSchema = {
  assetType: 'earthmoving',
  displayName: 'Earthmoving',
  subtypes: [
    { key: 'excavator',    label: 'Excavator' },
    { key: 'dozer',        label: 'Dozer' },
    { key: 'grader',       label: 'Grader' },
    { key: 'wheel_loader', label: 'Wheel Loader' },
    { key: 'skid_steer',   label: 'Skid Steer / CTL' },
    { key: 'backhoe',      label: 'Backhoe' },
    { key: 'telehandler',  label: 'Telehandler' },
  ],
  hasGlassValuation: false,
  fields: [
    { key: 'pin',                 label: 'PIN',                sfOrder: 1,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Build plate: Product Identification Number (PIN). Alphanumeric, typically 17 chars for Cat. Never infer — only extract if visible.' },
    { key: 'serial',              label: 'Serial',             sfOrder: 2,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Build plate: Serial Number. Format varies by manufacturer. Never infer — only extract if directly visible.' },
    { key: 'vin',                 label: 'VIN',                sfOrder: 3,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Build plate or chassis: 17-character VIN if present. Many earthmoving machines use PIN instead of VIN. Never infer.' },
    { key: 'type',                label: 'Type',               sfOrder: 4,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'make',                label: 'Make',               sfOrder: 5,  inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Build plate: manufacturer name (e.g. Caterpillar, Komatsu, Hitachi, Volvo, Liebherr, John Deere, CASE).' },
    { key: 'hourmeter',           label: 'Hourmeter',          sfOrder: 6,  inputType: 'number',   aiExtractable: false, inspectionPriority: true, required: false },
    { key: 'model',               label: 'Model',              sfOrder: 7,  inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Build plate: model designation (e.g. 320D, PC200, ZX200, EC220, LiG952H). Read exactly as printed.' },
    { key: 'year',                label: 'Year',               sfOrder: 8,  inputType: 'number',   aiExtractable: true,  required: true,  aiHint: 'Build plate: Year of Manufacture or DOM. 4-digit year only. May be deduced from serial number prefix for some manufacturers.' },
    { key: 'odometer',            label: 'Odometer',           sfOrder: 9,  inputType: 'number',   aiExtractable: false, inspectionPriority: true, required: false },
    { key: 'engine_manufacturer', label: 'Engine Manufacturer',sfOrder: 10, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Build plate or engine badge. Infer from make/model (e.g. Cat→Caterpillar, Komatsu→Komatsu/SAA, Volvo→Volvo D-series).' },
    { key: 'engine_model',        label: 'Engine Model',       sfOrder: 11, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer from make/model/year (e.g. Cat C7.1, Komatsu SAA6D107, Cummins QSB6.7). Model-specific constant.' },
    { key: 'engine_number',       label: 'Engine Number',      sfOrder: 12, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'horsepower',          label: 'Horsepower',         sfOrder: 13, inputType: 'number',   aiExtractable: true,  required: false, aiHint: 'Infer from make/model/year. Digits only, no units (e.g. 168 for Cat 320D). Known spec for common machines.' },
    { key: 'gross_hp',            label: 'Gross HP',           sfOrder: 14, inputType: 'number',   aiExtractable: true,  required: false, aiHint: 'Infer from make/model/year. Gross HP is slightly higher than net HP. Digits only.' },
    { key: 'fuel_type',           label: 'Fuel Type',          sfOrder: 15, inputType: 'select',   options: ['Diesel', 'Petrol', 'Electric', 'LPG'], aiExtractable: true,  required: false, aiHint: 'Earthmoving equipment is almost always Diesel. Only return non-Diesel if clearly evidenced (e.g. electric excavator badge).' },
    { key: 'emissions_tier',      label: 'Emissions Tier',     sfOrder: 16, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer from year: Tier 4 Final (post-2014), Tier 4 Interim (2011–2014), Tier 3 (2006–2011). Australia may be 1 year behind US.' },
    { key: 'drive_type',          label: 'Drive Type',         sfOrder: 17, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer from subtype and model: Crawlers are Track Drive, wheel loaders/graders are 4WD. e.g. Track Drive, 4WD.' },
    { key: 'transmission',        label: 'Transmission',       sfOrder: 18, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer from make/model (e.g. Cat automatic planetary, Komatsu PCSS, ZF powershift). Common: Automatic, Powershift, Hydrostatic.' },
    { key: 'speeds',              label: 'Speeds',             sfOrder: 19, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'torque_rpm',          label: 'Torque RPM',         sfOrder: 20, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'boom_length',         label: 'Boom Length',        sfOrder: 21, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'steering',            label: 'Steering',           sfOrder: 22, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'final_drive',         label: 'Final Drive',        sfOrder: 23, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'cabin',               label: 'Cabin',              sfOrder: 24, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'operator_station',    label: 'Operator Station',   sfOrder: 25, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'attachments',         label: 'Attachments',        sfOrder: 26, inputType: 'textarea', aiExtractable: false, required: false },
    { key: 'config',              label: 'Config',             sfOrder: 27, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'screen_size',         label: 'Screen Size',        sfOrder: 28, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'tare',                label: 'Tare',               sfOrder: 29, inputType: 'number',   aiExtractable: true,  required: false, aiHint: 'Operating weight from machine specs. Digits only in kg. Well-documented for common models (e.g. Cat 320D ≈ 21000 kg).' },
    { key: 'capacity',            label: 'Capacity',           sfOrder: 30, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'rims',                label: 'Rims',               sfOrder: 31, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'pto',                 label: 'PTO',                sfOrder: 32, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'remotes',             label: 'Remotes',            sfOrder: 33, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'extras',              label: 'Extras',             sfOrder: 34, inputType: 'textarea', aiExtractable: false, required: false },
  ],
  descriptionTemplate: (_fields, _subtype) => '',
}
