import type { AssetSchema } from '../types'

export const forkliftSchema: AssetSchema = {
  assetType: 'forklift',
  displayName: 'Forklift',
  subtypes: [
    { key: 'counterbalance', label: 'Counterbalance' },
    { key: 'reach_truck',    label: 'Reach Truck' },
    { key: 'order_picker',   label: 'Order Picker' },
    { key: 'telehandler',    label: 'Telehandler' },
  ],
  hasGlassValuation: false,
  fields: [
    { key: 'engine_manufacturer', label: 'Engine Manufacturer', sfOrder: 1,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Badge or infer from make/model (e.g. Toyota→Toyota, Linde→Linde electric, Komatsu→Komatsu, Crown→Crown electric).' },
    { key: 'engine_model',        label: 'Engine Model',        sfOrder: 2,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Data plate or infer from make/model (e.g. Linde E50→electric motor, Toyota 7FBE20→electric, Komatsu FB20→Komatsu).' },
    { key: 'engine_number',       label: 'Engine Number',       sfOrder: 3,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'vin',                 label: 'VIN',                 sfOrder: 4,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Data plate or chassis: VIN if present. Never infer — only extract if directly visible.' },
    { key: 'serial',              label: 'Serial',              sfOrder: 5,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Data plate: Serial Number. Typically alphanumeric. Never infer — only extract if directly visible.' },
    { key: 'max_lift_capacity',   label: 'Max Lift Capacity',   sfOrder: 6,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Forklift data plate: rated load capacity. Format: number with unit (e.g. 2500kg, 5T). Also inferrable from model number suffix.' },
    { key: 'max_lift_height',     label: 'Max Lift Height',     sfOrder: 7,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Forklift data plate or mast specs: maximum lift height. Format: number with unit (e.g. 4500mm, 4.5m).' },
    { key: 'make',                label: 'Make',                sfOrder: 8,  inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Data plate or cab badge: manufacturer name (e.g. Toyota, Linde, Komatsu, Crown, Hyster, Yale, Jungheinrich).' },
    { key: 'hours',               label: 'Hours',               sfOrder: 9,  inputType: 'number',   aiExtractable: false, inspectionPriority: true, required: false },
    { key: 'model',               label: 'Model',               sfOrder: 10, inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Data plate: model designation (e.g. 7FBE20, E50, FB20, C5000, H50FT). Read exactly as printed.' },
    { key: 'cabin',               label: 'Cabin',               sfOrder: 11, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'year',                label: 'Year',                sfOrder: 12, inputType: 'number',   aiExtractable: true,  required: true,  aiHint: 'Data plate: Year of Manufacture or DOM. 4-digit year only.' },
    { key: 'attachments',         label: 'Attachments',         sfOrder: 13, inputType: 'textarea', aiExtractable: false, required: false },
    { key: 'tilt_degrees',        label: 'Tilt Degrees',        sfOrder: 14, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'colour',              label: 'Colour',              sfOrder: 15, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Exterior colour from photos. Common forklift colours: Yellow, Orange, Red, Blue, White, Green. Use brand colour as default if visible.' },
    { key: 'truck_weight',        label: 'Truck Weight',        sfOrder: 16, inputType: 'number',   aiExtractable: false, required: false },
    { key: 'transmission',        label: 'Transmission',        sfOrder: 17, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer from make/model and fuel type. Electric: Electric Drive. LPG/Diesel: Automatic Torque Converter or Hydrostatic.' },
    { key: 'tyres',               label: 'Tyres',               sfOrder: 18, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'fuel_type',           label: 'Fuel Type',           sfOrder: 19, inputType: 'select',   options: ['Diesel', 'LPG', 'Electric', 'Petrol'], aiExtractable: true,  required: false, aiHint: 'Data plate or battery/engine type. Common: Electric, LPG, Diesel, Petrol. Electric forklifts have visible battery compartment.' },
    { key: 'stages',              label: 'Stages',              sfOrder: 20, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'type',                label: 'Type',                sfOrder: 21, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'mast_type',           label: 'Mast Type',           sfOrder: 22, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'extras',              label: 'Extras',              sfOrder: 23, inputType: 'textarea', aiExtractable: false, required: false },
  ],
  descriptionTemplate: (_fields, _subtype) => '',
}
