import type { AssetSchema } from '../types'

export const forkliftSchema: AssetSchema = {
  assetType: 'forklift',
  displayName: 'Forklift',
  subtypes: [
    { key: 'counterbalance', label: 'Counterbalance' },
    { key: 'reach_truck',    label: 'Reach Truck' },
    { key: 'order_picker',   label: 'Order Picker' },
    { key: 'telehandler',    label: 'Telehandler' },
  ],
  hasGlassValuation: false,
  fields: [
    { key: 'engine_manufacturer', label: 'Engine Manufacturer', sfOrder: 1,  inputType: 'text',     aiExtractable: true,  required: false },
    { key: 'engine_model',        label: 'Engine Model',        sfOrder: 2,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'engine_number',       label: 'Engine Number',       sfOrder: 3,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'vin',                 label: 'VIN',                 sfOrder: 4,  inputType: 'text',     aiExtractable: true,  required: false },
    { key: 'serial',              label: 'Serial',              sfOrder: 5,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false },
    { key: 'max_lift_capacity',   label: 'Max Lift Capacity',   sfOrder: 6,  inputType: 'text',     aiExtractable: false, inspectionPriority: true, required: false },
    { key: 'max_lift_height',     label: 'Max Lift Height',     sfOrder: 7,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'make',                label: 'Make',                sfOrder: 8,  inputType: 'text',     aiExtractable: true,  required: true  },
    { key: 'hours',               label: 'Hours',               sfOrder: 9,  inputType: 'number',   aiExtractable: false, inspectionPriority: true, required: false },
    { key: 'model',               label: 'Model',               sfOrder: 10, inputType: 'text',     aiExtractable: true,  required: true  },
    { key: 'cabin',               label: 'Cabin',               sfOrder: 11, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'year',                label: 'Year',                sfOrder: 12, inputType: 'number',   aiExtractable: true,  required: true  },
    { key: 'attachments',         label: 'Attachments',         sfOrder: 13, inputType: 'textarea', aiExtractable: false, required: false },
    { key: 'tilt_degrees',        label: 'Tilt Degrees',        sfOrder: 14, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'colour',              label: 'Colour',              sfOrder: 15, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'truck_weight',        label: 'Truck Weight',        sfOrder: 16, inputType: 'number',   aiExtractable: false, required: false },
    { key: 'transmission',        label: 'Transmission',        sfOrder: 17, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'tyres',               label: 'Tyres',               sfOrder: 18, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'fuel_type',           label: 'Fuel Type',           sfOrder: 19, inputType: 'select',   options: ['Diesel', 'LPG', 'Electric', 'Petrol'], aiExtractable: false, required: false },
    { key: 'stages',              label: 'Stages',              sfOrder: 20, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'type',                label: 'Type',                sfOrder: 21, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'mast_type',           label: 'Mast Type',           sfOrder: 22, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'extras',              label: 'Extras',              sfOrder: 23, inputType: 'textarea', aiExtractable: false, required: false },
  ],
  descriptionTemplate: (_fields, _subtype) => '',
}
