import type { AssetSchema } from '../types'

export const forkliftSchema: AssetSchema = {
  assetType: 'forklift',
  displayName: 'Forklift',
  subtypes: [
    { key: 'clearview_mast',       label: 'Clearview Mast' },
    { key: 'container_mast',       label: 'Container Mast' },
    { key: 'electric_pallet_jack', label: 'Electric Pallet Jack' },
    { key: 'ewp',                  label: 'EWP' },
    { key: 'other',                label: 'Other' },
    { key: 'stock_picker',         label: 'Stock Picker' },
    { key: 'telehandler',          label: 'Telehandler' },
    { key: 'walk_behind',          label: 'Walk Behind' },
    { key: 'walkie_stacker',       label: 'Walkie Stacker' },
  ],
  hasGlassValuation: false,
  fields: [
    { key: 'engine_manufacturer', label: 'Engine Manufacturer', sfOrder: 1,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Engine bay badge or infer from make/fuel: Toyota/LPG→Toyota, Linde electric→Linde, Komatsu→Komatsu, Hyster LPG→Hyster/Mazda, Yale→Mazda/Nissan.' },
    { key: 'engine_model',        label: 'Engine Model',        sfOrder: 2,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Data plate on mast or engine bay. Infer from make/model: Toyota 7FBE20→electric motor, Toyota 42-7FGF25→4Y LPG, Linde H50D→diesel, Komatsu FB20→electric.' },
    { key: 'engine_number',       label: 'Engine Number',       sfOrder: 3,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'vin',                 label: 'VIN',                 sfOrder: 4,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Data plate on mast column or overhead guard: VIN field if present. Never infer — only extract if directly visible.' },
    { key: 'serial',              label: 'Serial',              sfOrder: 5,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Data plate on mast column or overhead guard: Serial Number field. Alphanumeric. Never infer — only extract if directly visible.' },
    { key: 'max_lift_capacity',   label: 'Max Lift Capacity',   sfOrder: 6,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Data plate on mast or overhead guard: rated load/capacity. Format: number + unit (e.g. 2500kg, 5T, 3.5T). Also readable from model suffix (e.g. FG25=2500kg).' },
    { key: 'max_lift_height',     label: 'Max Lift Height',     sfOrder: 7,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Data plate on mast: free lift and max lift height. Format: number + unit (e.g. 4500mm, 6.0m). Measure mast stage count × stage height if labelled.' },
    { key: 'make',                label: 'Make',                sfOrder: 8,  inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Data plate on mast/overhead guard or exterior badge: make (e.g. Toyota, Linde, Komatsu, Crown, Hyster, Yale, Jungheinrich, TCM, Mitsubishi, Nissan).' },
    { key: 'hours',               label: 'Hours',               sfOrder: 9,  inputType: 'number',   aiExtractable: false, inspectionPriority: true, required: false },
    { key: 'model',               label: 'Model',               sfOrder: 10, inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Data plate on mast column or overhead guard: model designation (e.g. 7FBE20, E50, H50FT, C5000, RX70-35). Read exactly as printed.' },
    { key: 'cabin',               label: 'Cabin',               sfOrder: 11, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'year',                label: 'Year',                sfOrder: 12, inputType: 'number',   aiExtractable: true,  required: true,  aiHint: 'Data plate on mast or overhead guard: Year of Manufacture or DOM. 4-digit year only. Estimate from serial number range if year field not visible.' },
    { key: 'attachments',         label: 'Attachments',         sfOrder: 13, inputType: 'textarea', aiExtractable: false, required: false },
    { key: 'tilt_degrees',        label: 'Tilt Degrees',        sfOrder: 14, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Data plate on mast or overhead guard: mast tilt range (e.g. 6°/5°, 5°F/5°B). Format: forward°/backward° or as printed on plate.' },
    { key: 'colour',              label: 'Colour',              sfOrder: 15, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Exterior body colour from photos. Common brand colours: Toyota=red, Linde=blue, Komatsu=yellow, Crown=yellow, Hyster=grey. Describe actual visible colour.' },
    { key: 'truck_weight',        label: 'Unladen Weight',      sfOrder: 16, inputType: 'number',   aiExtractable: false, inspectionPriority: true, required: false },
    { key: 'transmission',        label: 'Transmission',        sfOrder: 17, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer from fuel type and make/model. Electric→Electric Drive, LPG/Diesel Toyota→Torque Converter Auto, Linde→Hydrostatic, Jungheinrich→AC Electric.' },
    { key: 'tyres',               label: 'Tyres',               sfOrder: 18, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Tyre sidewall or visual from photos: type and size. Common types: Pneumatic, Solid (press-on), Cushion. Size format: e.g. 6.00-9, 7.00-12, 18x7-8.' },
    { key: 'fuel_type',           label: 'Fuel Type',           sfOrder: 19, inputType: 'select',   options: ['Diesel', 'LPG', 'Electric', 'Petrol'], aiExtractable: true,  required: false, aiHint: 'Data plate or visible clues: battery compartment=Electric, LPG cylinder bracket=LPG, exhaust pipe=Diesel/Petrol. Common: warehouse=Electric, outdoor=LPG or Diesel.' },
    { key: 'stages',              label: 'Stages',              sfOrder: 20, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Count mast rail sections visible in photos: 2=Duplex, 3=Triplex, 4=Quadruplex. Most common is Duplex or Triplex. State as number (e.g. 2, 3).' },
    { key: 'type',                label: 'Type',                sfOrder: 21, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'mast_type',           label: 'Mast Type',           sfOrder: 22, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Mast section visible in photos: Simplex (1-stage), Duplex (2-stage), Triplex (3-stage, most common), Quad (4-stage), Full Free Lift (FFT). Infer from stage count if visible.' },
    { key: 'extras',              label: 'Extras',              sfOrder: 23, inputType: 'textarea', aiExtractable: false, required: false },
  ],
  descriptionTemplate: (_fields, _subtype) => '',
}
