import type { AssetSchema } from '../types'

export const trailerSchema: AssetSchema = {
  assetType: 'trailer',
  displayName: 'Trailer',
  subtypes: [
    { key: 'box',                       label: 'Box' },
    { key: 'car_carrier',               label: 'Car Carrier' },
    { key: 'coupe',                     label: 'Coupe' },
    { key: 'curtainsider',              label: 'Curtainsider' },
    { key: 'deck_widener',              label: 'Deck Widener' },
    { key: 'dog',                       label: 'Dog' },
    { key: 'dolly',                     label: 'Dolly' },
    { key: 'flat_deck',                 label: 'Flat Deck' },
    { key: 'low_loader',                label: 'Low Loader' },
    { key: 'other',                     label: 'Other' },
    { key: 'pantech',                   label: 'Pantech' },
    { key: 'pig',                       label: 'Pig' },
    { key: 'plant',                     label: 'Plant' },
    { key: 'refrigerated_curtainsider', label: 'Refrigerated Curtainsider' },
    { key: 'refrigerated_pantech',      label: 'Refrigerated Pantech' },
    { key: 'side_loader',               label: 'Side Loader' },
    { key: 'side_tipper',               label: 'Side Tipper' },
    { key: 'skel',                      label: 'Skel' },
    { key: 'stock',                     label: 'Stock' },
    { key: 'tag',                       label: 'Tag' },
    { key: 'tanker',                    label: 'Tanker' },
    { key: 'timber_jinker',             label: 'Timber Jinker' },
    { key: 'tipper',                    label: 'Tipper' },
    { key: 'walking_floor',             label: 'Walking Floor' },
  ],
  hasGlassValuation: false,
  fields: [
    { key: 'make',            label: 'Make',            sfOrder: 1,  inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Build plate riveted to drawbar (A-frame) or front chassis cross-member. Common Australian trailer manufacturers: Vawdrey, Maxitrans (Freighter/Maxi-CUBE), Lusty EMS, Barker, Krueger, Hamelex White, Drake, Southern Cross, Howard Porter, O\'Phee, Moore, Stoodley, Byrne, Tefco, Rhino, Fruehauf. Also check rear mud-flap logos and side-panel decals for brand confirmation.' },
    { key: 'model',           label: 'Model',           sfOrder: 2,  inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Build plate: model/type designation. Read exactly as printed (e.g. ST3, B-Double Lead, A-Trailer, Drop-Deck, Super-B). May be short code — include any alphanumeric suffix.' },
    { key: 'vin',             label: 'VIN',             sfOrder: 3,  inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Build plate on drawbar or front chassis rail: exactly 17-char alphanumeric VIN (no I, O, Q). Never infer — only extract if directly visible.' },
    { key: 'type',            label: 'Type',            sfOrder: 4,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer trailer type from exterior photos and subtype. e.g. Semi-Trailer, B-Double Lead, B-Double Rear, Dog Trailer, Tag Trailer, Dolly, Pig Trailer.' },
    { key: 'chassis_number',  label: 'Chassis Number',  sfOrder: 5,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Build plate or stamped on drawbar/chassis rail. Alphanumeric, length varies. Never infer — only extract if directly visible.' },
    { key: 'colour',          label: 'Colour',          sfOrder: 6,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Dominant exterior body/curtain colour from any exterior photo. Use simple names: White, Silver, Red, Blue, Black, Yellow, Orange, Grey. Two-tone: e.g. White/Blue.' },
    { key: 'body_type',       label: 'Body Type',       sfOrder: 7,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Infer from exterior photos. e.g. Curtainsider, Flat Deck, Drop Deck, Refrigerated Van, Pantech, Tipper, Side Tipper, Skeletal, Walking Floor, Stock Crate, Tanker, Car Carrier.' },
    { key: 'compliance_date', label: 'Compliance Date', sfOrder: 8,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Australian compliance plate (small metal plate on drawbar or chassis). Look for "Date of Manufacture" or "DOM". Format MM/YYYY (e.g. 06/2018).' },
    { key: 'year',            label: 'Year',            sfOrder: 9,  inputType: 'number',   aiExtractable: true,  required: true,  aiHint: 'Build plate "Year of Manufacture" or "DOM". 4-digit year only. Also deducible from VIN position 10 (model-year code).' },
    { key: 'registration',    label: 'Registration',    sfOrder: 10, inputType: 'text',     aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Registration plate on rear or front of trailer. Australian format varies by state (e.g. NSW: T12345, VIC: trailer plate). Null if no plate visible.' },
    { key: 'trailer_length',  label: 'Trailer Length',  sfOrder: 11, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Build plate or compliance plate "Length" or "Overall Length" field. Infer from trailer type if plate not visible: standard semi-trailer=13.6m; B-double lead=12.3m; B-double rear=12.3m; dog trailer=8–10m; pig trailer=6–8m; dolly=2–3m. Format: e.g. 13.6m.' },
    { key: 'hubometer',       label: 'Hubometer',       sfOrder: 12, inputType: 'number',   aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Hubometer device mounted on axle hub or wheel — small circular mechanical counter showing distance. Digits only in km. Extract only if clearly readable in photo.' },
    { key: 'height',          label: 'Height',          sfOrder: 13, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Build plate or compliance plate "Height" or "Overall Height" field. Format: e.g. 4.3m. Common semi-trailer heights: 4.2m–4.6m. Null if not on plate.' },
    { key: 'rims',            label: 'Rims',            sfOrder: 14, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Visible from tyre/wheel area photos. Common types: Steel (Budd), Alloy, Stainless steel. e.g. "Steel Budd", "Alloy", "Alcoa Alloy". Null if not visible.' },
    { key: 'suspension',      label: 'Suspension',      sfOrder: 15, inputType: 'select',   options: ['Spring', 'Airbag', '6 Rod', 'Other'], aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Under-trailer photos: visible airbag bags at axle ends = Airbag (most modern trailers). Leaf springs = Spring. Must be exactly: Spring, Airbag, 6 Rod, or Other. Default Airbag for trailers post-2000.' },
    { key: 'atm',             label: 'ATM',             sfOrder: 16, inputType: 'number',   aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Australian compliance plate field labelled "ATM" (Aggregate Trailer Mass). Digits only in kg (e.g. 42500). Standard compliance plate field — look on drawbar or front chassis.' },
    { key: 'axle_config',     label: 'Axle Config',     sfOrder: 17, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Count axle groups from exterior side photos. Format: Single (1 axle), Tandem (2 axles), Tri-Axle (3 axles), Quad-Axle (4 axles). Include spread if visible (e.g. Spread Tandem).' },
    { key: 'tare',            label: 'Tare',            sfOrder: 18, inputType: 'number',   aiExtractable: true,  inspectionPriority: true, required: false, aiHint: 'Build plate or compliance plate field labelled "Tare" or "Tare Mass". Digits only in kg (e.g. 8500). Common semi-trailer tares: curtainsiders 7,000–9,500 kg, flat decks 6,000–8,000 kg.' },
    { key: 'power',           label: 'Power',           sfOrder: 19, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'brakes',          label: 'Brakes',          sfOrder: 20, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'All semi-trailers use air brakes — never hydraulic. Infer type from age/make: pre-2010→Air Drum (S-Cam); post-2010 Vawdrey/Maxitrans premium→Air Disc (BPW/Knorr-Bremse); budget brands→Air Drum. Look for disc caliper at wheel hub vs drum housing. Add EBS if post-2012 premium (electronic brake distribution). e.g. "Air Drum", "Air Disc, EBS".' },
    { key: 'tyre_size',       label: 'Tyre Size',       sfOrder: 21, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Tyre sidewall markings on any trailer tyre. Standard format: width/aspect R rim-diameter (e.g. 11R22.5, 315/80R22.5, 245/70R17.5). Read from sidewall if visible in photos.' },
    { key: 'pin_sizes',       label: 'PIN Sizes',       sfOrder: 22, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Kingpin size visible on the kingpin itself or build plate. Standard: 2" (50mm) or 3.5" (90mm). Also note if dolly/dog has turntable pin. e.g. "2 inch", "3.5 inch".' },
    { key: 'extras',          label: 'Extras',          sfOrder: 23, inputType: 'textarea', aiExtractable: false, required: false },
  ],
  descriptionTemplate: (_fields, _subtype) => '',
}
