import type { AssetSchema } from '../types'

export const trailerSchema: AssetSchema = {
  assetType: 'trailer',
  displayName: 'Trailer',
  subtypes: [
    { key: 'flat_top',     label: 'Flat Top' },
    { key: 'drop_deck',    label: 'Drop Deck' },
    { key: 'side_tipper',  label: 'Side Tipper' },
    { key: 'dog_trailer',  label: 'Dog Trailer' },
    { key: 'b_double',     label: 'B-Double' },
    { key: 'semi_trailer', label: 'Semi-Trailer' },
  ],
  hasGlassValuation: false,
  fields: [
    { key: 'make',            label: 'Make',            sfOrder: 1,  inputType: 'text',     aiExtractable: true,  required: true  },
    { key: 'model',           label: 'Model',           sfOrder: 2,  inputType: 'text',     aiExtractable: true,  required: true  },
    { key: 'vin',             label: 'VIN',             sfOrder: 3,  inputType: 'text',     aiExtractable: true,  required: false },
    { key: 'type',            label: 'Type',            sfOrder: 4,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'chassis_number',  label: 'Chassis Number',  sfOrder: 5,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'colour',          label: 'Colour',          sfOrder: 6,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'body_type',       label: 'Body Type',       sfOrder: 7,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'compliance_date', label: 'Compliance Date', sfOrder: 8,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'year',            label: 'Year',            sfOrder: 9,  inputType: 'number',   aiExtractable: true,  required: true  },
    { key: 'registration',    label: 'Registration',    sfOrder: 10, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'trailer_length',  label: 'Trailer Length',  sfOrder: 11, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'hubometer',       label: 'Hubometer',       sfOrder: 12, inputType: 'number',   aiExtractable: false, required: false },
    { key: 'height',          label: 'Height',          sfOrder: 13, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'rims',            label: 'Rims',            sfOrder: 14, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'suspension',      label: 'Suspension',      sfOrder: 15, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'atm',             label: 'ATM',             sfOrder: 16, inputType: 'number',   aiExtractable: false, required: false },
    { key: 'axle_config',     label: 'Axle Config',     sfOrder: 17, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'tare',            label: 'Tare',            sfOrder: 18, inputType: 'number',   aiExtractable: false, required: false },
    { key: 'power',           label: 'Power',           sfOrder: 19, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'brakes',          label: 'Brakes',          sfOrder: 20, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'tyre_size',       label: 'Tyre Size',       sfOrder: 21, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'pin_sizes',       label: 'PIN Sizes',       sfOrder: 22, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'extras',          label: 'Extras',          sfOrder: 23, inputType: 'textarea', aiExtractable: false, required: false },
  ],
  descriptionTemplate: (_fields, _subtype) => '',
}
