import type { AssetSchema } from '../types'

export const truckSchema: AssetSchema = {
  assetType: 'truck',
  displayName: 'Truck',
  subtypes: [
    { key: 'beavertail',           label: 'Beavertail' },
    { key: 'cab_chassis',          label: 'Cab Chassis' },
    { key: 'concrete_agitator',    label: 'Concrete - Agitator' },
    { key: 'concrete_pump',        label: 'Concrete - Pump' },
    { key: 'coupe',                label: 'Coupe' },
    { key: 'crane_truck',          label: 'Crane Truck' },
    { key: 'curtainsider',         label: 'Curtainsider' },
    { key: 'ewp',                  label: 'EWP' },
    { key: 'flat_deck',            label: 'Flat Deck' },
    { key: 'fuel_truck',           label: 'Fuel Truck' },
    { key: 'garbage',              label: 'Garbage' },
    { key: 'hook_bin',             label: 'Hook Bin' },
    { key: 'other',                label: 'Other' },
    { key: 'pantech',              label: 'Pantech' },
    { key: 'prime_mover',          label: 'Prime Mover' },
    { key: 'refrigerated_pantech', label: 'Refrigerated Pantech' },
    { key: 'service_truck',        label: 'Service Truck' },
    { key: 'skip_bin',             label: 'Skip Bin' },
    { key: 'stock_truck',          label: 'Stock Truck' },
    { key: 'tanker',               label: 'Tanker' },
    { key: 'tipper',               label: 'Tipper' },
    { key: 'tilt_tray',            label: 'Tilt Tray' },
    { key: 'tray_truck',           label: 'Tray Truck' },
    { key: 'vacuum',               label: 'Vacuum' },
    { key: 'water_truck',          label: 'Water Truck' },
  ],
  hasGlassValuation: false,
  fields: [
    { key: 'chassis_number',      label: 'Chassis Number',      sfOrder: 1,  inputType: 'text',     aiExtractable: true,  aiHint: 'Build plate or stamped directly on chassis rail (driver-side, near front axle). Alphanumeric, length varies by make. Never infer — only extract if directly visible.', required: false },
    { key: 'vin',                 label: 'VIN',                  sfOrder: 2,  inputType: 'text',     aiExtractable: true,  aiHint: 'Build plate (under bonnet or door jamb) or compliance plate: exactly 17-char alphanumeric (no I, O, Q). Also stamped on chassis rail. Never infer — only extract if visible.', inspectionPriority: true, required: false },
    { key: 'make',                label: 'Make',                 sfOrder: 3,  inputType: 'text',     aiExtractable: true,  aiHint: 'Build plate or cab badge. Common Australian heavy truck makes: Kenworth, Mack, Volvo, Freightliner, Western Star, Mercedes-Benz, DAF, Isuzu, Hino, MAN, Scania, UD.', required: true  },
    { key: 'model',               label: 'Model',                sfOrder: 4,  inputType: 'text',     aiExtractable: true,  aiHint: 'Build plate or cab badge. Read exactly as printed (e.g. T908, T410, Granite, FH16, Actros, XF105, FVZ, 500 Series, NLR, NQR). Include numeric suffix.', required: true  },
    { key: 'year',                label: 'Year',                 sfOrder: 5,  inputType: 'number',   aiExtractable: true,  aiHint: 'Build plate field labelled "Year of Manufacture", "DOM", or "Build Date". 4-digit year only. Also deducible from VIN position 10 (model-year code).', required: true  },
    { key: 'cab_type',            label: 'Cab Type',             sfOrder: 6,  inputType: 'text',     aiExtractable: true,  aiHint: 'Infer from exterior cab shape: Day Cab (no sleeper box behind cab), Sleeper (raised/extended roof behind cab), Crew Cab (extra rear doors). Infer confidently from photos.', required: false },
    { key: 'gearbox_make',        label: 'Gearbox Make',         sfOrder: 7,  inputType: 'text',     aiExtractable: true,  aiHint: 'Badge on gearbox housing or infer from make/model: Mack→mDrive or Eaton, Volvo→I-Shift, Kenworth/Peterbilt→Eaton Fuller or Paccar TX, Freightliner→Detroit DT12 or Allison, Isuzu/Hino→Allison or ZF.', required: false },
    { key: 'drive_type',          label: 'Drive Type',           sfOrder: 8,  inputType: 'text',     aiExtractable: true,  aiHint: 'Build plate "Drive" field or count axles/wheels in under-vehicle photos. Format: 6x4, 4x2, 8x4, 6x2, 6x6. First digit = total axle-ends, second = driven. Most prime movers are 6x4.', required: false },
    { key: 'engine_manufacturer', label: 'Engine Manufacturer',  sfOrder: 9,  inputType: 'text',     aiExtractable: true,  aiHint: 'Cam cover badge or infer from make: Kenworth→Cummins/PACCAR, Mack→Mack, Volvo→Volvo, Freightliner/W-Star→Detroit, Mercedes→Mercedes-Benz, DAF→DAF, Hino→Hino, Isuzu→Isuzu.', required: false },
    { key: 'engine_series',       label: 'Engine Series',        sfOrder: 10, inputType: 'text',     aiExtractable: true,  aiHint: 'Cam cover badge or infer: KW T908→X15; Mack Granite→MP8; Volvo FH→D13; Actros→OM471; DAF XF→MX-13; Freightliner→DD15; Hino 300→N04C; Hino 500→J08E; Hino 700→E13C; Isuzu NPR→4HK1; Isuzu FVZ→6UZ1.', required: false },
    { key: 'engine_type',         label: 'Engine Type',          sfOrder: 11, inputType: 'text',     aiExtractable: true,  aiHint: 'Infer from engine series. Nearly all modern heavy trucks: Turbodiesel Inline-6. Older Mack/Detroit: Turbodiesel V8. e.g. "Turbodiesel Inline-6", "Turbodiesel V8".', required: false },
    { key: 'engine_number',       label: 'Engine Number',        sfOrder: 12, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'engine_size',         label: 'Engine Size',          sfOrder: 13, inputType: 'text',     aiExtractable: true,  aiHint: 'Build plate or badge. Format: e.g. 15.0L. Infer from series: X15→15.0L, MP8→12.8L, D13→12.8L, OM471→12.8L, MX-13→12.9L, DD15→14.8L, N04C→4.0L, J08E→7.7L, E13C→12.9L, 4HK1→5.2L, 6UZ1→9.8L.', required: false },
    { key: 'fuel_type',           label: 'Fuel Type',            sfOrder: 14, inputType: 'select',   options: ['Diesel', 'Petrol', 'Electric', 'LPG', 'CNG'], aiExtractable: true,  aiHint: 'Virtually all heavy trucks are Diesel. Only return non-Diesel if clearly evidenced: LPG/CNG badge or filler, visible electric drivetrain. Default to Diesel.', required: false },
    { key: 'variant',             label: 'Variant',              sfOrder: 15, inputType: 'text',     aiExtractable: true,  aiHint: 'Build plate "Variant" or "Type" field (e.g. GU500, T404ST, FH540, 2642LS). Read exactly as printed including power suffix. Null if not visible.', required: false },
    { key: 'compliance_date',     label: 'Compliance Date',      sfOrder: 16, inputType: 'text',     aiExtractable: true,  aiHint: 'Build plate "DOM"/"Date of Manufacture" or compliance plate (silver/gold, door jamb or under bonnet). Format MM/YYYY (e.g. 03/2012). Build plate date acceptable if no compliance plate visible.', required: false },
    { key: 'odometer',            label: 'Odometer',             sfOrder: 17, inputType: 'number',   aiExtractable: true,  aiHint: 'Instrument cluster digital or analog odometer. Digits only, no units. Extract only if clearly readable in dashboard photo — do NOT guess. Typical range 100,000–1,500,000 km.', inspectionPriority: true, required: false },
    { key: 'registration_number', label: 'Registration Number',  sfOrder: 18, inputType: 'text',     aiExtractable: true,  aiHint: 'Front or rear registration plate. Australian format varies by state (e.g. NSW: ABC123, VIC: 1AB2CD, QLD: 123AB4). Null if no plate is visible in any photo.', inspectionPriority: true, required: false },
    { key: 'colour',              label: 'Colour',               sfOrder: 20, inputType: 'text',     aiExtractable: true,  aiHint: 'Dominant exterior cab colour from any exterior photo. Use simple colour names: White, Red, Blue, Yellow, Orange, Green, Silver, Grey, Black. Two-tone: e.g. White/Blue.', required: false },
    { key: 'body_type',           label: 'Body Type',            sfOrder: 21, inputType: 'text',     aiExtractable: true,  aiHint: 'Body or tray visible in exterior photos (e.g. Tipper, Steel Tipper, Aluminium Tipper, Flat Deck, Tray, Curtainsider, Tanker, Crane, Service Body, Pantech). Null if prime mover/cab-chassis only.', required: false },
    { key: 'hourmeter',           label: 'Hourmeter',            sfOrder: 22, inputType: 'number',   aiExtractable: true,  aiHint: 'Instrument cluster hour meter (labelled "HRS" or clock icon). Digits only. Extract only if clearly readable — do NOT guess. Common on crane trucks, concrete agitators, EWPs.', inspectionPriority: true, required: false },
    { key: 'tyre_size',           label: 'Tyre Size',            sfOrder: 23, inputType: 'text',     aiExtractable: true,  aiHint: 'Tyre sidewall of steer axle tyres. Standard format: width/aspect ratio R rim-diameter (e.g. 315/80R22.5, 295/80R22.5, 11R22.5, 12R22.5). Read from sidewall if visible.', required: false },
    { key: 'transmission',        label: 'Transmission',         sfOrder: 24, inputType: 'text',     aiExtractable: true,  aiHint: 'Gear selector or infer from make/model/year. KW/Mack 2010+→Automated Manual; Volvo→I-Shift; Freightliner→DT12; pre-2010→Manual (Eaton Fuller 13/18-spd); Allison where fitted. e.g. "Automated Manual (Eaton UltraShift)".', required: false },
    { key: 'rims',                label: 'Rims',                 sfOrder: 25, inputType: 'text',     aiExtractable: true,  aiHint: 'Visible from tyre/wheel photos. Common types: Steel (Budd), Aluminium Alloy, Stainless. Note multi-piece if visible. e.g. "Alloy", "Steel Budd", "Alcoa Alloy".', required: false },
    { key: 'suspension',          label: 'Suspension',           sfOrder: 26, inputType: 'select',   options: ['Spring', 'Airbag', '6 Rod', 'Other'], aiExtractable: true,  aiHint: 'Rear/under-vehicle photos: rubber airbags at axle ends = Airbag; leaf springs = Spring. Kenworth/Mack offer both. Must be exactly one of: Spring, Airbag, 6 Rod, Other.', inspectionPriority: true, required: false },
    { key: 'axle_configuration',  label: 'Axle Configuration',   sfOrder: 27, inputType: 'text',     aiExtractable: true,  aiHint: 'Build plate or count axles in exterior photos. Same as drive_type — format: 6x4, 4x2, 8x4, 6x2. First digit = total wheel-ends ÷ 2, second = driven. Most semi-tractors: 6x4.', required: false },
    { key: 'brakes',              label: 'Brakes',               sfOrder: 28, inputType: 'text',     aiExtractable: true,  aiHint: 'Heavy trucks almost universally use air brakes with S-Cam drum actuation. Return "Air/S-Cam" unless disc calipers visible at wheels. Add "ABS" if post-2010 model. e.g. "Air/S-Cam", "Air/S-Cam, ABS", "Air Disc".', required: false },
    { key: 'gcm',                 label: 'GCM',                  sfOrder: 29, inputType: 'number',   aiExtractable: true,  aiHint: 'Build plate field labelled "GCM" (Gross Combination Mass). Digits only in kg (e.g. 68000, 85500). Infer from axle config if plate not visible: 6x4 prime mover typically 68,000–85,500 kg GCM.', required: false },
    { key: 'gvm',                 label: 'GVM',                  sfOrder: 30, inputType: 'number',   aiExtractable: true,  aiHint: 'Build plate field labelled "GVM" (Gross Vehicle Mass). Digits only in kg (e.g. 23000, 26000). Infer from make/model if plate not visible: heavy prime movers typically 22,000–26,000 kg GVM.', required: false },
    { key: 'nw',                  label: 'NW',                   sfOrder: 31, inputType: 'number',   aiExtractable: true,  aiHint: 'Build plate field labelled "NW" or "Tare" or "Nett Weight". Digits only in kg. Less commonly printed — null if not found on plate.', required: false },
    { key: 'service_history',     label: 'Service History',      sfOrder: 32, inputType: 'text',     aiExtractable: false, inspectionPriority: true, required: false },
    { key: 'extras',              label: 'Extras',               sfOrder: 33, inputType: 'textarea', aiExtractable: false, required: false },
  ],
  descriptionTemplate: (_fields, _subtype) => {
    // Stub — Phase 5 implements full deterministic template
    return ''
  },
}
