import type { AssetSchema } from '../types'

export const truckSchema: AssetSchema = {
  assetType: 'truck',
  displayName: 'Truck',
  subtypes: [
    { key: 'prime_mover',    label: 'Prime Mover' },
    { key: 'rigid_truck',    label: 'Rigid Truck' },
    { key: 'tipper',         label: 'Tipper' },
    { key: 'service_truck',  label: 'Service Truck' },
    { key: 'crane_truck',    label: 'Crane Truck' },
  ],
  hasGlassValuation: false,
  fields: [
    { key: 'chassis_number',      label: 'Chassis Number',      sfOrder: 1,  inputType: 'text',     aiExtractable: false, required: false },
    { key: 'vin',                 label: 'VIN',                  sfOrder: 2,  inputType: 'text',     aiExtractable: true,  aiHint: 'Build plate or compliance plate: 17-character alphanumeric. Also stamped on chassis rail. Never infer — only extract if visible.', inspectionPriority: true, required: false },
    { key: 'make',                label: 'Make',                 sfOrder: 3,  inputType: 'text',     aiExtractable: true,  aiHint: 'Build plate: manufacturer name (e.g. MACK, Kenworth, Volvo, Isuzu, Hino, Mercedes-Benz, DAF).', required: true  },
    { key: 'model',               label: 'Model',                sfOrder: 4,  inputType: 'text',     aiExtractable: true,  aiHint: 'Build plate: model designation (e.g. Granite, T908, FH16, NLR). Read exactly as printed.', required: true  },
    { key: 'year',                label: 'Year',                 sfOrder: 5,  inputType: 'number',   aiExtractable: true,  aiHint: 'Build plate: "Year of Manufacture" or "DOM" (Date of Manufacture). 4-digit year only.', required: true  },
    { key: 'cab_type',            label: 'Cab Type',             sfOrder: 6,  inputType: 'text',     aiExtractable: true,  aiHint: 'Visual from exterior photos. Common values: Day Cab, Sleeper, Crew Cab. Infer from shape if not labelled.', required: false },
    { key: 'gearbox_make',        label: 'Gearbox Make',         sfOrder: 7,  inputType: 'text',     aiExtractable: true,  aiHint: 'Badge on gearbox or infer from make/model (e.g. MACK mDrive, Volvo I-Shift, Eaton Fuller, ZF, Allison).', required: false },
    { key: 'drive_type',          label: 'Drive Type',           sfOrder: 8,  inputType: 'text',     aiExtractable: true,  aiHint: 'Build plate or infer from model. Format: 6x4, 4x2, 8x4, 6x2. Count driven axles from under-vehicle photos.', required: false },
    { key: 'engine_manufacturer', label: 'Engine Manufacturer',  sfOrder: 9,  inputType: 'text',     aiExtractable: true,  aiHint: 'Engine badge or build plate. Infer from make/model if not visible (e.g. MACK→MACK/MP8, Kenworth→Cummins/PACCAR).', required: false },
    { key: 'engine_series',       label: 'Engine Series',        sfOrder: 10, inputType: 'text',     aiExtractable: true,  aiHint: 'Badge or infer from make/model/year — you should almost always be able to provide this. e.g. MACK Granite→MP8, Kenworth T908→ISX15 or X15, Volvo FH→D13, Mercedes Actros→OM471, DAF XF→MX-13, Freightliner→DD15, Western Star→DD15 or C15, Hino 300→N04C, Hino 500→J08E, Hino 700→E13C, Isuzu NPR/NQR→4HK1, Isuzu FVZ→6UZ1. Return the engine family code only.', required: false },
    { key: 'engine_type',         label: 'Engine Type',          sfOrder: 11, inputType: 'text',     aiExtractable: true,  aiHint: 'Infer from make/model: typically "Turbodiesel Inline-6". Use engine family name if known (e.g. MP8 Turbodiesel).', required: false },
    { key: 'engine_number',       label: 'Engine Number',        sfOrder: 12, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'engine_size',         label: 'Engine Size',          sfOrder: 13, inputType: 'text',     aiExtractable: true,  aiHint: 'Build plate or badge. Format: displacement in litres with one decimal (e.g. 12.7L, 15.0L, 13.0L). Infer from engine series if not visible — e.g. MP8→12.8L, ISX15/X15→15.0L, D13→12.8L, OM471→12.8L, MX-13→12.9L, DD15→14.8L, C15→15.2L, N04C→4.0L, J08E→7.7L, E13C→12.9L, 4HK1→5.2L, 6UZ1→9.8L.', required: false },
    { key: 'fuel_type',           label: 'Fuel Type',            sfOrder: 14, inputType: 'select',   options: ['Diesel', 'Petrol', 'Electric', 'LPG', 'CNG'], aiExtractable: true,  aiHint: 'Heavy trucks are almost always Diesel. Only return non-Diesel if there is clear evidence (e.g. LPG badge, electric motor).', required: false },
    { key: 'variant',             label: 'Variant',              sfOrder: 15, inputType: 'text',     aiExtractable: true,  aiHint: 'Build plate variant or series field (e.g. GU500, T404ST, FH540). Read exactly as printed. Null if not visible.', required: false },
    { key: 'compliance_date',     label: 'Compliance Date',      sfOrder: 16, inputType: 'text',     aiExtractable: true,  aiHint: 'Check build plate for "Date of Manufacture", "DOM", or "Build Date" fields. Also check compliance plate (silver/gold plate inside door or under bonnet). Format MM/YYYY. e.g. 03/2012. The build plate date is acceptable if no separate compliance plate is visible.', required: false },
    { key: 'odometer',            label: 'Odometer',             sfOrder: 17, inputType: 'number',   aiExtractable: true,  aiHint: 'Instrument cluster display. Digits only, no units. Only extract if clearly readable — do NOT guess.', inspectionPriority: true, required: false },
    { key: 'registration_number', label: 'Registration Number',  sfOrder: 18, inputType: 'text',     aiExtractable: true,  aiHint: 'Registration plate on front or rear of vehicle. Australian format varies by state. Null if no plate visible.', inspectionPriority: true, required: false },
    { key: 'colour',              label: 'Colour',               sfOrder: 20, inputType: 'text',     aiExtractable: true,  aiHint: 'Exterior cab colour from photos. Use common colour names (White, Red, Blue, Yellow, Orange, Green, Silver, Black).', required: false },
    { key: 'body_type',           label: 'Body Type',            sfOrder: 21, inputType: 'text',     aiExtractable: true,  aiHint: 'Body fitted to chassis from exterior photos (e.g. Tipper, Flat Deck, Curtainsider, Tanker, Crane, Service). Null if prime mover only.', required: false },
    { key: 'hourmeter',           label: 'Hourmeter',            sfOrder: 22, inputType: 'number',   aiExtractable: true,  aiHint: 'Instrument cluster hour meter display. Digits only. Only extract if clearly readable — do NOT guess.', inspectionPriority: true, required: false },
    { key: 'tyre_size',           label: 'Tyre Size',            sfOrder: 23, inputType: 'text',     aiExtractable: true,  aiHint: 'Tyre sidewall markings. Format: width/aspect R diameter (e.g. 315/80R22.5, 11R22.5). Use steer tyres as reference.', required: false },
    { key: 'transmission',        label: 'Transmission',         sfOrder: 24, inputType: 'text',     aiExtractable: true,  aiHint: 'Infer from make/model/year (e.g. Automated Manual, Manual, Automatic). Common: mDrive, I-Shift, Eaton UltraShift, Allison.', required: false },
    { key: 'rims',                label: 'Rims',                 sfOrder: 25, inputType: 'text',     aiExtractable: false, required: false },
    { key: 'suspension',          label: 'Suspension',           sfOrder: 26, inputType: 'select',   options: ['Spring', 'Airbag', '6 Rod', 'Other'], aiExtractable: true,  aiHint: 'Infer from model or visible from under-vehicle photos. Must be exactly one of: Spring, Airbag, 6 Rod, Other.', inspectionPriority: true, required: false },
    { key: 'axle_configuration',  label: 'Axle Configuration',   sfOrder: 27, inputType: 'text',     aiExtractable: true,  aiHint: 'Build plate or infer from visual. Format: number of axles × driven (e.g. 6x4, 4x2, 8x4). Same as drive_type.', required: false },
    { key: 'brakes',              label: 'Brakes',               sfOrder: 28, inputType: 'text',     aiExtractable: true,  aiHint: 'Infer from make/model: heavy trucks use air brakes with S-Cam drum actuation. Always return "Air/S-Cam" unless there is clear evidence of disc brakes. Note ABS if known from model year. e.g. "Air/S-Cam", "Air/S-Cam, ABS".', required: false },
    { key: 'gcm',                 label: 'GCM',                  sfOrder: 29, inputType: 'number',   aiExtractable: true,  aiHint: 'Build plate as "GCM" (Gross Combination Mass). Digits only in kg (e.g. 68000). Infer from axle config if needed.', required: false },
    { key: 'gvm',                 label: 'GVM',                  sfOrder: 30, inputType: 'number',   aiExtractable: true,  aiHint: 'Build plate as "GVM" (Gross Vehicle Mass). Digits only in kg (e.g. 23000). Infer from make/model if plate not visible.', required: false },
    { key: 'nw',                  label: 'NW',                   sfOrder: 31, inputType: 'number',   aiExtractable: true,  aiHint: 'Build plate as "NW" or "Nett Weight". Digits only in kg. Less commonly visible — null if not found.', required: false },
    { key: 'service_history',     label: 'Service History',      sfOrder: 32, inputType: 'text',     aiExtractable: false, inspectionPriority: true, required: false },
    { key: 'extras',              label: 'Extras',               sfOrder: 33, inputType: 'textarea', aiExtractable: false, required: false },
  ],
  descriptionTemplate: (_fields, _subtype) => {
    // Stub — Phase 5 implements full deterministic template
    return ''
  },
}
