import type { AssetSchema } from '../types'

export const vehicleSchema: AssetSchema = {
  assetType: 'vehicle',
  displayName: 'Vehicle',
  subtypes: [
    { key: 'dual_cab_ute',    label: 'Dual Cab Ute' },
    { key: 'single_cab_ute',  label: 'Single Cab Ute' },
    { key: 'extra_cab_ute',   label: 'Extra Cab Ute' },
    { key: 'sedan',           label: 'Sedan' },
    { key: 'suv',             label: 'SUV' },
    { key: 'wagon',           label: 'Wagon' },
    { key: 'hatchback',       label: 'Hatchback' },
    { key: 'van',             label: 'Van' },
    { key: 'coupe',           label: 'Coupe' },
    { key: 'convertible',     label: 'Convertible' },
    { key: '4wd',             label: '4WD / Off-Road' },
    { key: 'bus',             label: 'Bus / Minibus' },
    { key: 'motorcycle',      label: 'Motorcycle' },
    { key: 'other',           label: 'Other' },
  ],
  hasGlassValuation: false,
  fields: [
    // ── Section: Asset Information ──
    { key: 'make',                label: 'Make',                  sfOrder: 1,  inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Badge on tailgate, grille, or steering wheel. Common Australian market makes: Toyota, Ford, Mazda, Hyundai, Kia, Nissan, Mitsubishi, Subaru, Holden (pre-2021), Isuzu, Volkswagen, Honda, Mercedes-Benz, BMW, Audi, Lexus, Land Rover, Jeep, Suzuki, Renault, Peugeot, Skoda, MG, GWM, LDV, SsangYong, Fiat, Volvo, Porsche, Tesla, BYD, Haval. Read exactly as badged.' },
    { key: 'vin',                 label: 'VIN',                   sfOrder: 2,  inputType: 'text',     aiExtractable: true,  required: false, inspectionPriority: true, aiHint: 'Build plate (door jamb, engine bay, or windscreen base): 17-character VIN. May be labelled "VIN", "Chassis No", or stamped on chassis rail. Never infer — only extract if directly visible.' },
    { key: 'variant',             label: 'Variant',               sfOrder: 3,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Badge on tailgate or boot lid — variant/trim level. Read exactly as badged. Common variants by make:\nToyota: WorkMate, SR, SR5, Rogue, Rugged X, GX, GXL, VX, Kakadu, Sahara, ZR, Ascent Sport, SX, Cruiser, Edge, Grande, Atara S/SX/SL\nFord: XL, XLS, XLT, Sport, Wildtrak, Raptor, Ambiente, Trend, Titanium, ST-Line, Vignale\nMazda: Neo, Maxx, Touring, GT, Akera, Evolve, SP25, Astina\nHyundai: Active, Elite, Highlander, N Line, Ultimate\nKia: S, Sport, Sport+, GT-Line, GT\nNissan: RX, ST, ST-L, ST-X, Ti, Ti-L, N-TREK, PRO-4X, Warrior\nMitsubishi: GLX, GLX+, GLS, GSR, Exceed, ES, LS, Aspire\nSubaru: 2.0i, 2.0i-L, 2.0i-S, 2.0i Premium, 2.5i-S, STI, WRX\nIsuzu: SX, LS-M, LS-U, LS-U+, X-Terrain\nVolkswagen: Trendline, Comfortline, Highline, Sportline, Aventura, R-Line\nHolden: LS, LT, LTZ, Z71, Storm, Colorado Z71\nMercedes: 200, 250, 300, 350, AMG, Classic, Avantgarde, AMG Line\nBMW: 118i, 120i, 320i, 330i, 520i, X1/X3/X5 sDrive/xDrive\nIf variant badge is not visible, infer from interior trim level, wheel style, or feature set if confident.' },
    { key: 'suspension',          label: 'Suspension',            sfOrder: 4,  inputType: 'select',   aiExtractable: true,  required: false, options: ['Airbag', 'Spring', 'Other'], aiHint: 'Infer from vehicle type: most passenger vehicles = Spring (coil/leaf). Commercial vans and heavy utes may have leaf spring rear. Air suspension on luxury SUVs (Range Rover, Mercedes GLS). Default to Spring for standard vehicles.' },
    { key: 'year',                label: 'Year of Manufacture',   sfOrder: 5,  inputType: 'number',   aiExtractable: true,  required: false, aiHint: 'Build plate or compliance plate: Year of Manufacture / DOM. 4-digit year. If not on plate, estimate from model generation using your training knowledge.' },
    { key: 'registration_number', label: 'Registration Number',   sfOrder: 6,  inputType: 'text',     aiExtractable: true,  required: false, inspectionPriority: true, aiHint: 'Registration plate on front or rear. Australian formats vary by state (NSW: XX-XX-XX, QLD: 123-ABC, VIC: XXX-000). Read exactly as shown.' },
    { key: 'chassis_number',      label: 'Chassis Number',        sfOrder: 7,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Stamped on chassis rail or build plate. May differ from VIN on older vehicles. Only extract if separately labelled — if same as VIN, return null.' },
    { key: 'engine_number',       label: 'Engine Number',         sfOrder: 8,  inputType: 'text',     aiExtractable: true,  required: false, inspectionPriority: true, aiHint: 'Stamped on engine block (usually near exhaust manifold side). Alphanumeric, varies by manufacturer. Only extract if directly visible.' },
    { key: 'engine_manufacturer', label: 'Engine Manufacturer',   sfOrder: 9,  inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Usually same as vehicle make. Key exceptions: Mazda BT-50 (2020+) uses Isuzu engine. Holden Colorado uses GM/Isuzu. LDV uses Maxus. GWM/Haval uses GWM. Most Japanese/Korean brands use their own engines. European brands use their own (Mercedes, BMW, VW group shares between VW/Audi/Skoda). Ford Ranger uses Ford-developed engines (not Mazda post-2011).' },

    // ── Section: Vehicle Specifications ──
    { key: 'model',               label: 'Model',                 sfOrder: 10, inputType: 'text',     aiExtractable: true,  required: true,  aiHint: 'Badge on tailgate or boot lid — model name only, NOT variant. Common models by make:\nToyota: Hilux, LandCruiser, Prado, RAV4, Corolla, Camry, Kluger, Fortuner, Yaris, C-HR, HiAce, HiLux, 86/GR86\nFord: Ranger, Everest, Focus, Escape, Mustang, Transit, Mondeo, Endura, Puma\nMazda: BT-50, CX-3, CX-5, CX-8, CX-9, CX-30, CX-60, Mazda2, Mazda3, Mazda6, MX-5\nHyundai: i30, Tucson, Santa Fe, Kona, Venue, Palisade, Staria, iLoad, iMax\nKia: Cerato, Sportage, Sorento, Seltos, Carnival, Stonic, EV6, Picanto\nNissan: Navara, Patrol, X-Trail, Pathfinder, Qashqai, Juke, Leaf\nMitsubishi: Triton, Pajero, Pajero Sport, Outlander, ASX, Eclipse Cross, Express\nIsuzu: D-Max, MU-X\nSubaru: Outback, Forester, XV/Crosstrek, WRX, Impreza, BRZ, Liberty\nVolkswagen: Amarok, Tiguan, Touareg, T-Cross, T-Roc, Golf, Polo, Transporter, Crafter\nRead exactly as badged. Do not combine model + variant.' },
    { key: 'series',              label: 'Series',                sfOrder: 11, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Model series/generation code on build plate. Examples:\nToyota Hilux: GUN125R/GUN126R/GUN136R (2015+), KUN26R (2005-15)\nToyota LandCruiser 200: VDJ200R (2007-21), 300: VJA300R (2021+)\nToyota Prado 150: GDJ150R (2015+), KDJ150R (2009-15)\nToyota RAV4: AXAH52R/AXAH54R (hybrid), MXAA52R (petrol)\nFord Ranger: PX MkI (2011-15), PX MkII (2015-18), PX MkIII (2018-22), Next-Gen (2022+)\nMazda BT-50: UR (2011-20), TF (2020+)\nMazda CX-5: KF (2017+), KE (2012-17)\nHyundai i30: PD (2017+), GD (2012-17)\nNissan Navara: D23 (2015+), D40 (2005-15)\nNissan Patrol: Y62 (2010+), Y61 (1997-2016)\nIsuzu D-Max: RG (2020+), TF (2012-20)\nInfer from make/model/year if not visible on plate.' },
    { key: 'transmission',        label: 'Transmission',          sfOrder: 12, inputType: 'select',   aiExtractable: true,  required: false, options: ['Automatic', 'Manual', 'CVT'], aiHint: 'Build plate or interior: P-R-N-D selector = Automatic. Clutch pedal = Manual. CVT common on: Subaru (Lineartronic), Nissan (Xtronic), Toyota Corolla (Direct Shift CVT), Honda.\nMost modern utes = 6-speed Auto (Hilux, Ranger, D-Max, Navara, Triton). Manual still available on base model utes.\nMost SUVs 2018+ = Automatic. Tesla/BYD = Automatic (single-speed).\nHyundai i30/Kia Cerato offer both DCT auto and manual.\nIf not visible, default to Automatic for 2018+ models.' },
    { key: 'drive_type',          label: 'Drive Type',            sfOrder: 13, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Badges: "4x4", "4WD", "AWD", "4MATIC", "xDrive", "Quattro", "ATTESA", "S-AWC", "i-AWD", "Symmetrical AWD". Infer from model:\n4WD: Hilux SR5/Rogue (4x4 variants), Ranger XLT/Wildtrak/Raptor, Prado, LandCruiser, D-Max LS-U+/X-Terrain, Patrol, Pajero\n2WD: Hilux WorkMate/SR (2x4 variants), Ranger XL (2WD), base model utes, most sedans/hatches\nAWD: Subaru (all models), RAV4 AWD, Kluger AWD, CX-5 AWD, Tucson AWD, Sportage AWD\nFWD: Corolla, i30, Cerato, Mazda3, most city cars\nRWD: 86/BRZ, BMW 3-series, Mercedes C-Class, Mustang' },
    { key: 'body',                label: 'Body',                  sfOrder: 14, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Body builder or configuration: "Alloy Tray", "Steel Tray", "Canopy", "Cab Chassis", "Service Body", etc. For standard passenger vehicles, return null — this field is for modified/commercial bodies.' },
    { key: 'body_type',           label: 'Body Type',             sfOrder: 15, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Visual identification: Sedan, Hatchback, SUV, Dual Cab Ute, Single Cab Ute, Van, Wagon, Coupe, Convertible, Bus, Cab Chassis.' },
    { key: 'compliance_date',     label: 'Compliance Date',       sfOrder: 16, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Compliance plate (door jamb or engine bay): format MM/YYYY. Australian compliance date — may differ from Year of Manufacture for imported vehicles.' },
    { key: 'registration_expiry', label: 'Registration Expiry',   sfOrder: 17, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Rego sticker on windscreen or plate. Format: MM/YYYY or DD/MM/YYYY.' },
    { key: 'colour',              label: 'Colour',                sfOrder: 18, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Exterior body colour from photos. Use common names (White, Silver, Black, Red, Blue, Grey, etc.). If two-tone, list both.' },
    { key: 'fuel_type',           label: 'Fuel Type',             sfOrder: 19, inputType: 'select',   aiExtractable: true,  required: false, options: ['Petrol', 'Diesel', 'LPG', 'Hybrid', 'Electric', 'Petrol and Gas'], aiHint: 'Build plate, fuel filler cap, or infer from model. Diesel badges: "TDI", "D4D", "CDI", "dCi", "CRDi", "BlueTEC", "D", "TD". Hybrid: "HEV", "PHEV", "Hybrid" badge, "e:" prefix. Electric: Tesla, BYD, no exhaust pipe.\nAlways Diesel: Hilux (most), Ranger, BT-50, D-Max, Triton, Navara, Prado (most), LandCruiser\nAlways Petrol: Patrol Y62, 86/GR86, BRZ, most Mazda3/6/CX-30, Yaris\nHybrid: RAV4 Hybrid, Kluger Hybrid, Corolla Hybrid, CX-60 PHEV\nBoth available (check badge): Hilux 2.7 Petrol vs 2.8 Diesel, Prado 2.7P vs 2.8D, HiAce 2.8D vs 3.5P\nDefault to Diesel for utes/commercial vehicles unless clear petrol indicators.' },

    // ── Section: Technical & Identification ──
    { key: 'engine_size',         label: 'Engine Size',           sfOrder: 20, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Build plate or engine bay: displacement. Infer from make/model/year if not on plate. Common engines:\nToyota Hilux: 2.8L (1GD-FTV diesel), 2.7L (2TR-FE petrol)\nToyota LandCruiser 300: 3.3L (F33A-FTV twin turbo diesel)\nToyota LandCruiser 200: 4.5L (1VD-FTV V8 twin turbo diesel)\nToyota Prado 150: 2.8L (1GD-FTV diesel), 2.7L (2TR-FE petrol)\nToyota RAV4: 2.5L (A25A-FXS hybrid), 2.0L (M20A-FKS petrol)\nFord Ranger: 2.0L Bi-Turbo/Single Turbo diesel, 3.0L V6 turbo diesel (next-gen)\nMazda BT-50: 3.0L (same as Isuzu 4JJ3-TCX)\nHyundai/Kia: 2.0L, 2.5L petrol, 2.2L CRDi diesel\nNissan Navara: 2.3L Twin Turbo diesel (YS23DDTT)\nNissan Patrol Y62: 5.6L V8 petrol (VK56VD)\nIsuzu D-Max: 3.0L (4JJ3-TCX turbo diesel)\nMitsubishi Triton: 2.4L (4N15 turbo diesel)\nSubaru: 2.0L/2.5L Boxer petrol, 2.0L turbo (WRX)' },
    { key: 'engine_type',         label: 'Engine Type',           sfOrder: 21, inputType: 'text',     aiExtractable: true,  required: false, aiHint: 'Engine configuration. Format as: "X-Cylinder [Turbo] Fuel Type" e.g. "4-Cylinder Turbo Diesel", "V8 Petrol", "4-Cylinder Petrol". Infer from make/model:\nMost utes/4WDs in Australia = 4-Cylinder Turbo Diesel\nNissan Patrol Y62 = V8 Petrol\nToyota LandCruiser 200 = V8 Twin Turbo Diesel\nToyota LandCruiser 300 = V6 Twin Turbo Diesel\nFord Ranger Raptor (next-gen) = V6 Twin Turbo Diesel\nMost small cars (i30, Corolla, Mazda3) = 4-Cylinder Petrol\nRAV4 Hybrid = 4-Cylinder Hybrid Petrol\nTesla/BYD = Electric Motor' },
    { key: 'master_key',          label: 'Master Key',            sfOrder: 22, inputType: 'select',   aiExtractable: false, required: false, options: ['Yes', 'No'] },
    { key: 'spare_key',           label: 'Spare Key',             sfOrder: 23, inputType: 'select',   aiExtractable: false, required: false, options: ['Yes', 'No'] },
    { key: 'odometer',            label: 'Odometer (km)',         sfOrder: 24, inputType: 'number',   aiExtractable: true,  required: false, inspectionPriority: true, aiHint: 'Instrument cluster: odometer reading in km. Read the full number exactly — digits only. If blurry or uncertain, return null.' },
    { key: 'gvm',                 label: 'GVM (kgs)',             sfOrder: 25, inputType: 'number',   aiExtractable: true,  required: false, aiHint: 'Build plate or door jamb: Gross Vehicle Mass in kg. Digits only. Infer from make/model knowledge for common vehicles.' },
    { key: 'gcm',                 label: 'GCM (kgs)',             sfOrder: 26, inputType: 'number',   aiExtractable: true,  required: false, aiHint: 'Build plate: Gross Combination Mass in kg. Usually only on vehicles rated for towing. Digits only.' },
    { key: 'owners_manual',       label: "Owner's Manual",        sfOrder: 27, inputType: 'select',   aiExtractable: false, required: false, options: ['Yes', 'No'] },

    // ── Section: Operational & Logistics ──
    { key: 'service_history',     label: 'Service History',       sfOrder: 28, inputType: 'select',   aiExtractable: false, required: false, options: ['Full Log Books', 'Partial Log Books', 'No Log Books', 'Unknown'] },
    { key: 'accessories',         label: 'Accessories',           sfOrder: 29, inputType: 'textarea', aiExtractable: true,  required: false, aiHint: 'Visible accessories from photos: bull bar, tow bar, roof racks, canopy, tonneau cover, side steps, spot lights, snorkel, winch, UHF radio, dash cam, cargo barrier.' },
    { key: 'extras',              label: 'Extras',                sfOrder: 30, inputType: 'textarea', aiExtractable: true,  required: false, aiHint: 'Features visible in interior/exterior photos: alloy wheels, sunroof, leather seats, heated seats, sat nav, reverse camera, parking sensors, Apple CarPlay, premium audio.' },

    // ── Section: Damage ──
    { key: 'driveable',           label: 'Driveable',             sfOrder: 31, inputType: 'select',   aiExtractable: false, required: false, options: ['Yes', 'No'] },
    { key: 'damage',              label: 'Damage',                sfOrder: 32, inputType: 'textarea', aiExtractable: true,  required: false, aiHint: 'Concise Salesforce-ready summary of ALL visible damage. Write exactly as Slattery staff would paste into Salesforce. Real examples: "Scratches and dents visible around vehicle", "Dent to driver side rear door, scratches to passenger side", "Minor scratches, stone chips to bonnet", "Damage to front bumper, cracked headlight LHS", "Hail damage evident across roof and bonnet". Use location terms: driver/passenger, front/rear, LHS/RHS. Combine multiple items with commas. Be specific but concise — one line, no bullet points. If no damage visible in any photo, return null.' },
    { key: 'damage_notes',        label: 'Damage Notes',          sfOrder: 33, inputType: 'textarea', aiExtractable: true,  required: false, aiHint: 'List each body panel and its damage. Format as "Panel - Damage" on each line. Only list panels where damage is visible. Example:\nFront Bumper - Stone chips, light scratches\nBonnet - Stone chips along leading edge\nDriver Front Guard - Deep scratch through paint\nDriver Rear Door - Dent approx 150mm\nRear Bumper - Scuff marks, minor crack LHS\nWindscreen - Stone chip lower LHS\nDo NOT list panels with no damage. Only include panels you can see damage on in the photos. Staff may also type mechanical damage or issues not visible in photos.' },
  ],
  descriptionTemplate: (_fields, _subtype) => '',
}
