import { describe, it, expect } from 'vitest'
import * as fs from 'fs'
import * as path from 'path'

import { BRAND } from '@/lib/constants/brand'

describe('BRAND config', () => {
  it('BRAND.name equals "Slattery Auctions"', () => {
    expect(BRAND.name).toBe('Slattery Auctions')
  })

  it('BRAND.logoMonogram equals "S"', () => {
    expect(BRAND.logoMonogram).toBe('S')
  })

  it('BRAND.appTitle equals "Slattery Auctions Book-in"', () => {
    expect(BRAND.appTitle).toBe('Slattery Auctions Book-in')
  })

  it('BRAND.appDescription equals "Asset book-in tool"', () => {
    expect(BRAND.appDescription).toBe('Asset book-in tool')
  })

  it('BRAND.reportHeader equals "Slattery Auctions \u2014 Condition Report"', () => {
    expect(BRAND.reportHeader).toBe('Slattery Auctions \u2014 Condition Report')
  })

  it('BRAND.reportFooter equals "Generated by Slattery Auctions Asset Book-In"', () => {
    expect(BRAND.reportFooter).toBe('Generated by Slattery Auctions Asset Book-In')
  })

  it('BRAND.domain equals "assetbookintool.com"', () => {
    expect(BRAND.domain).toBe('assetbookintool.com')
  })

  it('all BRAND values are non-empty strings', () => {
    for (const [key, value] of Object.entries(BRAND)) {
      expect(typeof value, `BRAND.${key} should be a string`).toBe('string')
      expect((value as string).length, `BRAND.${key} should be non-empty`).toBeGreaterThan(0)
    }
  })
})

describe('BRAND smoke tests', () => {
  function collectFiles(dir: string, exts: string[]): string[] {
    const results: string[] = []
    if (!fs.existsSync(dir)) return results
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const fullPath = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        results.push(...collectFiles(fullPath, exts))
      } else if (exts.some(ext => entry.name.endsWith(ext))) {
        results.push(fullPath)
      }
    }
    return results
  }

  it('no hardcoded assetbookintool.com in consumer files', () => {
    const srcDir = path.resolve(__dirname, '..')
    const dirs = [path.join(srcDir, 'components'), path.join(srcDir, 'app')]
    const files = dirs.flatMap(d => collectFiles(d, ['.tsx', '.ts']))
    const matches = files.filter(f => {
      if (f.includes('brand.ts')) return false
      const content = fs.readFileSync(f, 'utf-8')
      return content.includes('assetbookintool.com')
    })
    expect(matches, `Hardcoded assetbookintool.com found in: ${matches.join(', ')}`).toHaveLength(0)
  })

  it('no hardcoded hex colors in component/app files', () => {
    // Hex values banned from component files — use semantic Tailwind tokens instead
    const BANNED_HEX = ['#F87171', '#166534', '#111f11', '#0a1a0a']

    const srcDir = path.resolve(__dirname, '..')
    const dirs = [path.join(srcDir, 'components'), path.join(srcDir, 'app')]
    const files = dirs.flatMap(d => collectFiles(d, ['.tsx', '.ts']))

    const violations: string[] = []

    for (const f of files) {
      // global-error.tsx is exempt: uses intentional inline styles before CSS loads
      if (f.endsWith('global-error.tsx')) continue
      // Skip test files (they reference hex as string literals being searched for)
      if (f.includes('.test.')) continue
      // Skip brand constants files
      if (f.endsWith('brand.ts')) continue

      const content = fs.readFileSync(f, 'utf-8')
      for (const hex of BANNED_HEX) {
        if (content.includes(hex)) {
          violations.push(`${f}: ${hex}`)
        }
      }
    }

    expect(violations, `Hardcoded hex found:\n${violations.join('\n')}`).toHaveLength(0)
  })

  it('global-error.tsx uses brand-matching #0f1f0f, not old #166534', () => {
    const globalErrorPath = path.resolve(__dirname, '..', 'app', 'global-error.tsx')
    if (!fs.existsSync(globalErrorPath)) return
    const content = fs.readFileSync(globalErrorPath, 'utf-8')
    expect(content).not.toContain('#166534')
    expect(content).toContain('#0f1f0f')
  })
})
