import { describe, it, expect } from 'vitest'
import * as fs from 'fs'
import * as path from 'path'

import { BRAND } from '@/lib/constants/brand'

describe('BRAND config', () => {
  it('BRAND.name equals "Slattery Auctions"', () => {
    expect(BRAND.name).toBe('Slattery Auctions')
  })

  it('BRAND.logoMonogram equals "S"', () => {
    expect(BRAND.logoMonogram).toBe('S')
  })

  it('BRAND.appTitle equals "Slattery Auctions Book-in"', () => {
    expect(BRAND.appTitle).toBe('Slattery Auctions Book-in')
  })

  it('BRAND.appDescription equals "Asset book-in tool"', () => {
    expect(BRAND.appDescription).toBe('Asset book-in tool')
  })

  it('BRAND.reportHeader equals "Slattery Auctions \u2014 Condition Report"', () => {
    expect(BRAND.reportHeader).toBe('Slattery Auctions \u2014 Condition Report')
  })

  it('BRAND.reportFooter equals "Generated by Slattery Auctions Asset Book-In"', () => {
    expect(BRAND.reportFooter).toBe('Generated by Slattery Auctions Asset Book-In')
  })

  it('BRAND.domain equals "assetbookintool.com"', () => {
    expect(BRAND.domain).toBe('assetbookintool.com')
  })

  it('all BRAND values are non-empty strings', () => {
    for (const [key, value] of Object.entries(BRAND)) {
      expect(typeof value, `BRAND.${key} should be a string`).toBe('string')
      expect((value as string).length, `BRAND.${key} should be non-empty`).toBeGreaterThan(0)
    }
  })
})

describe('BRAND smoke tests', () => {
  function collectFiles(dir: string, exts: string[]): string[] {
    const results: string[] = []
    if (!fs.existsSync(dir)) return results
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const fullPath = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        results.push(...collectFiles(fullPath, exts))
      } else if (exts.some(ext => entry.name.endsWith(ext))) {
        results.push(fullPath)
      }
    }
    return results
  }

  it.skip('no hardcoded assetbookintool.com in consumer files (unskip after Task 2)', () => {
    const srcDir = path.resolve(__dirname, '..')
    const dirs = [path.join(srcDir, 'components'), path.join(srcDir, 'app')]
    const files = dirs.flatMap(d => collectFiles(d, ['.tsx', '.ts']))
    const matches = files.filter(f => {
      if (f.includes('brand.ts')) return false
      const content = fs.readFileSync(f, 'utf-8')
      return content.includes('assetbookintool.com')
    })
    expect(matches, `Hardcoded assetbookintool.com found in: ${matches.join(', ')}`).toHaveLength(0)
  })

  it.skip('no hardcoded hex #F87171 in component files (unskip in Plan 02)', () => {
    const srcDir = path.resolve(__dirname, '..')
    const dirs = [path.join(srcDir, 'components'), path.join(srcDir, 'app')]
    const files = dirs.flatMap(d => collectFiles(d, ['.tsx', '.ts']))
    const matches = files.filter(f => {
      const content = fs.readFileSync(f, 'utf-8')
      return content.includes('#F87171')
    })
    expect(matches, `Hardcoded #F87171 found in: ${matches.join(', ')}`).toHaveLength(0)
  })
})
